homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret zhome_latitude
  longitude: !secret zhome_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 118
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  customize: !include_dir_merge_named customizations
  packages: !include_dir_named packages
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
     api_password: !secret http_password

# Show links to resources in log and frontend
#introduction:
# logger:
#   default: info
#   logs:
#     homeassistant.components.device_tracker: critical
#     homeassistant.components.ios: critical

# Enables the frontend
frontend:
  themes: !include themes.yaml

mobile_app:

# Enable Floorplan UI
# panel_custom:
#   - name: floorplan
#     sidebar_title: Floorplan
#     sidebar_icon: mdi:home
#     url_path: floorplan
#     config: !include floorplan.yaml

hacs:
  token: !secret github-token

# custom_updater:
#   component_urls:
# # Released build
#     - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json

# panel_iframe:
#   motioneye:
#     title: motioneye
#     icon: mdi:cctv
#     url: "https://192.168.100.185:8765"

#   # tv_room_ha:
#   #   title: TV Room HA
#   #   icon: mdi:home-assistant
#   #   url: !secret tv_room_ha_url
#   # cockpit_gui:
#   #   title: Cockpit GUI
#   #   icon: mdi:view-dashboard
#   #   url: !secret cockpit_gui_url
#   snapcast_server:
#     title: Snapcast Server
#     icon: mdi:music
#     url: 'http://192.168.100.12' #!secret snapcast_server_url

map:
config:
person:
cloud:
  alexa:
    filter:
      # include_entities:
      #   - light.bruce_lamp
      #   - light.lene_lamp
      include_domains:
        - switch
        - light
        - fan
      exclude_entities:
        - switch.outside
    entity_config:
      scene.bedroom_morning:
        name: Good Morning
        description: Turn on the bedroom lamps
      scene.bedroom_goodnight:
        name: Good night
        description: Turn off the bedroom lamps
      switch.monitors:
        display_categories: SMARTPLUG
        name: Office monitors
      switch.salt_lamp:
        display_categories: SMARTPLUG
        name: Fireplace
      script.radio_stop:
        name: Stop Comfort Noise
        display_categories: SCENE_TRIGGER
      script.radio_start:
        name: Start Comfort noise
        display_categories: SCENE_TRIGGER

http:
  # Uncomment this to add a password (recommended!)
    # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: False
  #login_attempts_threshold: 5

# Checks for available updates
updater:
  include_used_components: true

breaking_changes:

# # Discover some devices automatically
# discovery:

# # Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
  purge_interval: 2
  purge_keep_days: 5

graphite:
  host: 192.168.100.185

media_extractor:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
#sensor:
#  platform: yr

# # Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: 'us-west-2'
    text_type: ssml
    cache: True

alexa:

wemo:

ios:
  push:
    categories:
      - name: Alarm
        identifier: 'ALARM'
        actions:
          - identifier: 'SOUND_ALARM'
            title: 'Sound Alarm'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
          - identifier: 'SILENCE_ALARM'
            title: 'Silence Alarm'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: no
            behavior: 'textInput'
            textInputButtonTitle: 'Silencio!'
            textInputPlaceholder: 'Placeholder'
      - name: Trash
        identifier: 'TRASH'
        actions:
          - identifier: 'Already_Done'
            title: 'Already set out'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: no
            behavior: 'default'
          - identifier: 'SILENCE_REMINDER'
            title: 'Snooze'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
            # textInputButtonTitle: 'Snnoze for?'
            # textInputPlaceholder: 'Placeholder'

emulated_hue:
  #type: alexa
  listen_port: 8300
  expose_by_default: false


#notify: !include_dir_named notifiers
# notify: !include notify.yaml


#################################################################
## Sensors
#################################################################
# sensor:
#   - platform: crimereports
#     exclude: ['Community Policing']
#     name: Neighborhood Incidents
#     radius: 300

# mqtt:
#   broker: !secret mqtt_server
#   port: !secret mqtt_port
#   username: !secret mqtt_user
#   password: !secret mqtt_password
#   discovery: true
#   discovery_prefix: homeassistant

zone: !include_dir_list zones
#   name: Home
#   latitude: !secret zhome_latitude
#   longitude: !secret zhome_longitude
#   radius: !secret zhome_radius
#
# zone 2:
#   name: Church
#   latitude: !secret zchurch_latitude
#   longitude: !secret zchurch_longitude
#   radius: !secret zchurch_radius
#
# zone 3:
#   name: school_cc
#   latitude: !secret zcc_latitude
#   longitude: !secret zcc_longitude
#   radius: !secret zcc_radius
#
# zone 4:
#   name: piano
#   latitude: !secret zpiano_latitude
#   longitude: !secret zpiano_longitude
#   radius: !secret zpiano_radius
# #  beacon:
# #    uuid: 7223e44fac664412b854fe50d72977ff
# #    major: 60042
# #    minor: 43814

automation: !include automation.yaml
group: !include groups.yaml
script: !include_dir_merge_named script
