homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret zhome_latitude
  longitude: !secret zhome_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 118
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  customize: !include_dir_merge_named customizations
  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:
# logger:
#   default: info
#   logs:
#     homeassistant.components.device_tracker: critical
#     homeassistant.components.ios: critical

# Enables the frontend
frontend: 
  themes: !include themes.yaml


# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url

# Checks for available updates
updater:
  include_used_components: true

# # Discover some devices automatically
discovery:

# # Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

recorder:
  purge_days: 14

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
#sensor:
#  platform: yr

# # Text to speech
tts:
  platform: google
  cache: true
  cache_dir: /tmp/tts
  time_memory: 300

ios:
  push:
    categories:
      - name: Alarm
        identifier: 'ALARM'
        actions:
          - identifier: 'SOUND_ALARM'
            title: 'Sound Alarm'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
          - identifier: 'SILENCE_ALARM'
            title: 'Silence Alarm'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: no
            behavior: 'textInput'
            textInputButtonTitle: 'Silencio!'
            textInputPlaceholder: 'Placeholder'
      - name: Trash
        identifier: 'TRASH'
        actions:
          - identifier: 'Already_Done'
            title: 'Already set out'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: no
            behavior: 'default'
          - identifier: 'SILENCE_REMINDER'
            title: 'Snooze'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
            # textInputButtonTitle: 'Snnoze for?'
            # textInputPlaceholder: 'Placeholder'

emulated_hue:
  type: alexa
  listen_port: 8300
  expose_by_default: false


device_tracker:
# - platform: icloud
#    username: bruce@reeves-kids.com
#    password: !secret iCloud
#    account_name: iCloud
  # - platform: nmap_tracker
  #   hosts: !secret nmap_hosts
  #   track_new_devices: no
  #   interval_seconds: 30
  #   consider_home: 60
  - platform: asuswrt
    host: !secret asus_host
    username: !secret asus_username
    password: !secret asus_password
    track_new_devices: no
    interval_seconds: 12
    consider_home: 180

  # - platform: locative

media_player:
  - platform: kodi
    host: !secret kodi_host
    name: Kodi_LV
    port: 80
  - platform: kodi
    host: !secret kodi_host_MB
    name: Kodi_MB
  # - platform: cast

#notify: !include_dir_named notifiers
notify: !include notify.yaml


#################################################################
## Sensors
#################################################################
sensor:
  # - platform: fitbit
  #   monitored_resources:
  #     - "activities/distance"
  #     - "activities/steps"
  #     - "sleep/startTime"
  #     - "sleep/timeInBed"
  #     - "devices/battery"
  - platform: crimereports
    exclude: ['Community Policing']
    name: Neighborhood Incidents
    radius: 300

mqtt:
  broker: !secret mqtt_server
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_password

zone:
  name: Home
  latitude: !secret zhome_latitude
  longitude: !secret zhome_longitude
  radius: !secret zhome_radius  

zone 2:  
  name: Church
  latitude: !secret zchurch_latitude
  longitude: !secret zchurch_longitude
  radius: !secret zchurch_radius  

zone 3:
  name: school_cc 
  latitude: !secret zcc_latitude
  longitude: !secret zcc_longitude
  radius: !secret zcc_radius  
#  beacon:
#    uuid: 7223e44fac664412b854fe50d72977ff
#    major: 60042
#    minor: 43814

automation: !include automation.yaml
group: !include groups.yaml


