default_view:
  view: true
  icon: mdi:home
  entities:
  - group.Household
  - group.Office
  - group.Devices
  - group.scenes


automation:
  name: Automation
  view: true
  icon: mdi:robot
  entities:
  - group.automation_override
  - group.automation_on_demand
  - group.location_controls

sensors:
  name: Sensors
  view: true
  icon: mdi:gauge
  entities:
   - group.household
  # - group.device_location
  # - group.device_location_testing
  # - group.weather
  # - group.indoor_temperature
  # - group.occupancy
  # - group.doors
  # - group.speedtest
   - group.system
  # - group.battery_levels


location:
  name: Location
  view: true
  icon: mdi:truck-delivery
  entities:
  - group.deliveries
  - group.transit
  - group.maps

misc_view:
  name: Misc
  view: yes
  icon: mdi:power
  entities:
    - group.sensor_battery_levels
    - group.utilities
    - group.backup
    - group.device_status
    - group.server_status
    - group.processes
    - group.restarts
    - group.ads_blocked
    - group.pi_zero
    - group.hassctl


Household:
- light.lene_lamp
- light.bruce_lamp
- input_boolean.trash
- input_boolean.weekly_trash_reminder
- media_player.living_Room
- media_player.living_room_2

Bedroom lamps:
- light.lene_lamp
- light.bruce_lamp

Automation Override:
- input_boolean.freezer
- input_boolean.disable_lock_unlock_doors
- input_boolean.disable_auto_garage
- input_boolean.plex_lights_disable
- input_boolean.rainy_day_disable
- input_boolean.occupancy_lights_off_disable
- input_boolean.door_open_lights_on
- input_boolean.occupancy_air_purifier_on_off_disable
- input_boolean.lights_morning_disable
- input_boolean.office_lights_sunset
- input_boolean.exterior_on_sunset
- input_boolean.exterior_off_night
- input_boolean.vacation_mode
- input_boolean.trash
- input_boolean.weekly_trash_reminder
- input_boolean.teatimer

Location Controls:
- input_boolean.bruceaway
- input_boolean.bruceaway_driving
- input_boolean.leneaway
- input_boolean.leneaway_driving
- input_boolean.brucehome
- input_boolean.lenehome


Automation On Demand:
- input_boolean.dash_input
- input_boolean.unlock_doors
- input_boolean.bedtime
- input_boolean.vacation_mode
- input_select.remote
- input_boolean.restart_hass
- input_boolean.test_notify

Devices:
- device_tracker.openelec
- device_tracker.freezer
- sensor.freenas
- device_tracker.brucesiphone2_ios
- device_tracker.leneiphone_ios
- device_tracker.breevs_ipad


