default_view:
  view: true
  icon: mdi:home
  entities:
  - group.doors
  - group.scenes
  - group.guest_bath
  - group.Household
  - group.entry_points
  - group.Devices
  - group.kitchen
  - group.Office
  - group.finance
  - group.climate
  - group.shellies


Alarm Clock:
  name: Alarm Clock
  view: true
  icon: mdi:clock
  entities:
    - group.controls
    - group.kids

nodes:
  name: Sensor Nodes
  view: yes
  icon: mdi:access-point-network
  entities:
    - group.sensor_node_1_card
    - group.sensor_node_2_card
    - group.sensor_node_3_card
    - group.sensor_node_4_card
    - group.zwave_devices
    - group.freezer
    - group.mb_heater


Radio_view:
  name: Radio
  view: yes
  icon: mdi:radio
  entities:
    - group.radio
    - group.radio_controls
    - group.players

location:
  name: Location
  view: true
  icon: mdi:truck-delivery
  entities:
  - group.deliveries
  - group.transit
  - group.maps

misc_view:
  name: Misc
  view: yes
  icon: mdi:power
  entities:
    - group.system
    - group.sabnzb
    - group.utilities
    - group.backup
    - group.processes
    - group.hassctl
    - group.pihole
    - group.wallpanel

automation:
  name: Automation
  view: true
  icon: mdi:robot
  entities:
  - group.automation_override
  - group.automation_on_demand
  - group.location_controls
  - group.alarm_automations

# sensors:
#   name: Sensors
#   view: true
#   icon: mdi:gauge
#   entities:
#    - group.household
#    - group.device_location
#    - group.device_location_testing
#   # - group.weather
#   # - group.indoor_temperature
#    - group.occupancy
#   # - group.doors
#   # - group.speedtest
#    - group.battery_levels

############################
# General/Global Groups
############################

Household:
  control: hidden
  name: Household Status
  entities:
    - light.lene_lamp
    - light.bruce_lamp
    - input_boolean.alarm_active
    - script.light_alert
    - input_boolean.windows_open
    - binary_sensor.garage_door
    - switch.christmas_tree
    - switch.landing_lights
    - switch.stairs_lights


Devices:
  control: hidden
  name: Devices
  entities:
    - sensor.openelec
    - sensor.freezer
    - device_tracker.freenas
    - sensor.bruce
    - sensor.lene
    - sensor.kahlan
    - device_tracker.recovery

Automation Override:
  control: hidden
  name: Automation Override
  entities:
    - input_boolean.gb_auto_off
    - input_boolean.freezer
    - input_boolean.disable_lock_unlock_doors
    - input_boolean.disable_auto_garage
    - input_boolean.plex_lights_disable
    - input_boolean.rainy_day_disable
    - input_boolean.occupancy_lights_off_disable
    - input_boolean.door_open_lights_on
    - input_boolean.occupancy_air_purifier_on_off_disable
    - input_boolean.lights_morning_disable
    - input_boolean.office_lights_sunset
    - input_boolean.exterior_on_sunset
    - input_boolean.exterior_off_night
    - switch.vacation_mode
    - input_boolean.trash
    - input_boolean.weekly_trash_reminder
    - input_boolean.teatimer
    - input_boolean.dash_input
    - input_boolean.unlock_doors
    - input_boolean.bedtime
    - input_select.remote
    - input_boolean.restart_hass
    - input_boolean.test_notify
    - input_boolean.bedroom_dash
    - sensor.last_message
