homeassistant:
  customize:
    switch.vacation_mode:
      icon: midi:airplane_takeoff
      emulated_hue_name: "Vacation Mode"
      emulated_hue: true

# input_boolean:
#   vacation_mode:
#     initial: off


switch:
  - platform: mqtt
    state_topic: "/home/mode/vacation"
    command_topic: "/home/mode/vacation"
    name: Vacation Mode
    icon: mdi:account-alert
    retain: yes
    payload_on: "on"
    payload_off: "off"

automation:
  - alias: 'Away mode On'
    initial_state: True
    trigger:
      - platform: state
        entity_id: switch.vacation_mode
        from: 'off'
        to: 'on'
    action:
      - service: notify.dev
        data_template:
          message: >
            {%- set responses = [
            'Have a good time, I got things covered while your away.',
            'What, you left again, why do I never get to go?',
            'YES SIR, on duty, protect and serve !!!'] -%}
            Bruce> {{ responses | random }}

  - alias: 'Away mode Off'
    initial_state: True
    trigger:
      - platform: state
        entity_id: switch.vacation_mode
        from: 'on'
        to: 'off'
    action:
      - service: notify.dev
        data_template:
          message: >
            {%- set responses = [
            'Did you have fun, I covered everything while your away.',
            'Well it is about time you came back around',
            'AFFIRMATIVE SIR, standing down!!!'] -%}
            Bruce> {{ responses | random }}

  - alias: 'Vacation mode radio On'
    initial_state: True
    condition:
      - condition: state
        entity_id: switch.vacation_mode
        state: 'on'
    trigger:
      - platform: sun
        event: sunrise
        offset: '-00:35:00'
    action:
      - service: homeassistant.turn_on
        entity_id:
          - group.Bedroom_lamps
      - service: script.radio_away
      - service: notify.dev
        data_template:
          message: >
            {%- set responses = [
            'It just tickles me pink to Start music and turn the lamps on',
            'Got you covered, vacation lights are on'] -%}
            Bruce> {{ responses | random }}

#################################################################
## Lights on 45 minutes before sunset
#################################################################

  - alias: 'Vacation mode lights On'
    initial_state: True
    condition:
      - condition: state
        entity_id: switch.vacation_mode
        state: 'on'
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:45:00'
    action:
      - service: homeassistant.turn_on
        entity_id:
          - group.Bedroom_lamps
          - group.kitchen_accent
          - switch.switch_2
          # - switch.monitors
          - switch.salt_lamp
          - switch.christmas_tree
          - switch.landing_lights
          - switch.stairs_lights
          - switch.office_light
      - service: script.radio_stop
      - service: notify.dev
        data_template:
          message: >
            {%- set responses = [
            'It just tickles me pink to remind you that I turned the lights on',
            'Well isn\'t it just a breath of fresh air to know I can take care of turning lights on while your away?',
            'Got you covered, vacation lights are on'] -%}
            Bruce> {{ responses | random }}
#################################################################
## Lights off 2 hours after sunset
#################################################################
  - alias: 'Vacation mode lights Off'
    initial_state: True
    condition:
      - condition: state
        entity_id: switch.vacation_mode
        state: 'on'
    trigger:
      - platform: sun
        event: sunset
        offset: '+02:00:00'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - group.Bedroom_lamps
          - group.kitchen_accent
          - switch.switch_2
          # - switch.monitors
          - switch.salt_lamp
          - switch.christmas_tree
          - switch.landing_lights
          - switch.stairs_lights
          - switch.office_light
      - service: script.radio_stop
      - service: notify.dev
        data_template:
          message: >
            {%- set responses = [
            'It just tickles me pink to remind you that I turned the lights off for you.',
            'Well isn\'t it just a breath of fresh air to know I can take care of turning lights off while your away?',
            'Got you covered, vacation lights are off.'] -%}
            Bruce> {{ responses | random }}
