homeassistant:
  customize:
    script.aquarium_scene:
      friendly_name: 'Aquarium'
      emulated_hue: true
      icon: mdi:fish
    script.sexy_time:
      friendly_name: 'Sexy Time'
      emulated_hue: true
      icon: mdi:heart
    script.river_scene:
      friendly_name: 'River'
      emulated_hue: true
      icon: mdi:hook
    script.beach_scene:
      friendly_name: 'Beach'
      emulated_hue: true
      icon: mdi:tower-beach
    script.jungle_scene:
      friendly_name: 'Jungle'
      emulated_hue: true
      icon: mdi:paw
    script.fireplace_scene:
      friendly_name: 'Fire Place'
      emulated_hue: true
      icon: mdi:fire
    scene.bedroom_on:
      friendly_name: 'Space'
      emulated_hue: true
      icon: mdi:earth
    scene.bedroom_goodnight:
      friendly_name: 'Fire Place'
      emulated_hue: true
      icon: mdi:fire

input_boolean:
  dash_input:
    name: Dash Button
    initial: on
    icon: mdi:light

group:
  scenes:
    control: hidden
    name: Live Scenes
    entities:
      - scene.Bedroom_on
      - scene.Bedroom_goodnight

scene:
  - name: Bedroom_on
    entities:
      light.bruce_lamp: on
      light.lene_lamp: on
  - name: Bedroom_goodnight
    entities:
      light.bruce_lamp: 
        state: off
        transition: 10
      light.lene_lamp: 
        state: off
        transition: 10    

automation:
- alias: 'Lamps Off'
  condition:
    - condition: state
      entity_id: input_boolean.dash_input
      state: 'on'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(states.input_boolean.dash_input.last_changed)) > 30 }}'
  trigger:
    - platform: state
      entity_id: input_boolean.dash_input
      to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.Bedroomgoodnight

- alias: 'Lamps On'
  condition:
    - condition: state
      entity_id: input_boolean.dash_input
      state: 'on'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(states.input_boolean.dash_input.last_changed)) > 30 }}'
  trigger:
    - platform: state
      entity_id: input_boolean.dash_input
      to: 'on'
  action:
   - service: scene.turn_on
     entity_id: scene.Bedroomnight

