

################################################################
## Package / Bedroom lights
################################################################



homeassistant:
  customize:
    light.bruce_lamp:
      emulated_hue: false
      icon: mdi:light
    light.lene_lamp:
      emulated_hue: false
      icon: mdi:light
    scene.bedroom_mornining:
      friendly_name: 'Morning lamps'
      emulated_hue: true
      icon: mdi:themer-light-dark
    scene.bedroom_goodnight:
      friendly_name: 'Good Night lamps'
      emulated_hue: true
      icon: theme-light-dark
    input_slider.bedroom_lamps_brightness:
      icon: mdi:lightbulb-on


input_boolean:
  bedroom_dash:
    name: Dash Button
    initial: on
    icon: mdi:light
# Define input_slider
input_number:
  bedroom_lamps_brightness:
    name: Brightness
    initial: 100
    min: 0
    max: 254
    step: 1
    mode: slider

timer:
  closet_light:
    duration: '00:00:30'

sensor:
  - platform: template
    sensors:
      kodi_mb:
        friendly_name: 'MB MediaCenter'
        value_template: "{{ 'Online' if is_state('device_tracker.libreelec', 'home') else 'Offline' }}"

group:
  scenes:
    control: hidden
    name: Bedroom Controls
    entities:
      - scene.bedroom_morning
      - script.good_morning
      - scene.Bedroom_goodnight
      - input_slider.bedroom_lamps_brightness
      - sensor.kodi_mb
      - media_player.kodi_mb
      - switch.mb_closet_light
      - timer.closet_light

  Bedroom lamps:
    control: hidden
    name: Bedroom Lamps
    entities:
      - light.lene_lamp
      - light.bruce_lamp

scene:
  - name: bedroom_morning
    entities:
      light.bruce_lamp:
        state: on
        transition: 10
        brightness: 250
      light.lene_lamp:
        state: on
        transition: 10
        brightness: 250
  - name: bedroom_goodnight
    entities:
      light.bruce_lamp:
        state: off
        transition: 5
      light.lene_lamp:
        state: off
        transition: 5

automation:
  - alias: 'Lamps Off'
    initial_state: True
    condition:
      - condition: state
        entity_id: group.bedroom_lamps
        state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.bedroom_dash
    action:
      - service: scene.turn_on
        entity_id: scene.bedroom_goodnight

  - alias: 'Lamps On'
    initial_state: True
    condition:
      - condition: state
        entity_id: group.bedroom_lamps
        state: 'off'
    trigger:
      - platform: state
        entity_id: input_boolean.bedroom_dash
    action:
     - service: scene.turn_on
       entity_id: scene.bedroom_morning


  - alias: Bedroom Lamps - Adjust Brightness
    initial_state: True
    trigger:
      platform: state
      entity_id: input_slider.bedroom_lamps_brightness
    action:
      - service: light.turn_on
        data_template:
          entity_id:
            - light.bruce_lamp
            - light.lene_lamp
          brightness: '{{ trigger.to_state.state | int }}'


######### Closet Light ###################

  - alias: 'Closet - Motion'
    initial_state: True
    trigger:
      - platform: state
        entity_id: binary_sensor.mb_closet_pir
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: switch.mb_closet_light
        state: 'off'
    action:
      # - service: timer.start
      #   entity_id: timer.closet_light
      - service: homeassistant.turn_on
        entity_id: switch.mb_closet_light

  - alias: 'Closet - Motion - start timer'
    initial_state: True
    trigger:
      - platform: state
        entity_id: binary_sensor.mb_closet_pir
        from: 'on'
        to: 'off'
    condition:
      - condition: state
        entity_id: switch.mb_closet_light
        state: 'on'
    action:
      - service: timer.start
        entity_id: timer.closet_light

  - alias: 'Closet - Motion - restart timer'
    initial_state: True
    trigger:
      - platform: state
        entity_id: binary_sensor.mb_closet_pir
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: switch.mb_closet_light
        state: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.closet_light

  - alias: 'Closet - timer - off'
    initial_state: True
    condition:
      - condition: state
        entity_id: switch.mb_closet_light
        state: 'on'
      # - condition: template
      #   value_template: '{{ (as_timestamp(now()) - as_timestamp(states.binary_sensor.mb_closet_pir.last_changed)) > 30 }}'
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.closet_light
    action:
      - service: homeassistant.turn_off
        entity_id: switch.mb_closet_light

  # - alias: 'Closet - On'
  #   initial_state: True
  #   condition:
  #     - condition: state
  #       entity_id: switch.mb_closet_light
  #       state: 'off'
  #     # - condition: template
  #     #   value_template: '{{ (as_timestamp(now()) - as_timestamp(states.binary_sensor.mb_closet_pir.last_changed)) > 30 }}'
  #   trigger:
  #     platform: event
  #     event_type: timer.start
  #     event_data:
  #       entity_id: timer.closet_light
  #   action:
  #     - service: homeassistant.turn_on
  #       entity_id: switch.mb_closet_light


  # - alias: 'Closet - Manual'
  #   initial_state: True
  #   trigger:
  #     - platform: state
  #       entity_id: switch.mb_closet_light
  #       from: 'off'
  #       to: 'on'
  #   action:
  #     - service: timer.start
  #       entity_id: timer.closet_light
