###################################
## [HikVision Cameras](http://amzn.to/2dcexIB)
###################################


homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'cameras'

      exposed: &exposed
        <<: *customize
        emulated_hue: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

# Driveway Camera
    binary_sensor.driveway_camera_motion:
      friendly_name: Driveway Camera Motion
    binary_sensor.driveway_camera_field_detection:
      friendly_name: Driveway Field Detection
    binary_sensor.driveway_camera_line_crossing:
      friendly_name: Driveway Line Crossing
    binary_sensor.driveway_camera_tamper_detection:
      friendly_name: Driveway Camera Tamper Detection

    group.camera_field_detection:
      <<: *hidden
    group.camera_line_crossing:
      <<: *hidden
    group.camera_tamper_detection:
      <<: *hidden

group:
  cameras:
    icon: mdi:video
    view: true
    entities:
    - camera.driveway_camera
    - group.skybell
    - group.camera_motion
    - group.camera_field_detection
    - group.camera_line_crossing
    - group.camera_tamper_detection


  Camera Motion:
    entities:
      - binary_sensor.frontdoor_camera_motion
      - binary_sensor.driveway_camera_motion
      - binary_sensor.patio_camera_motion
      - binary_sensor.playarea_camera_motion

  Camera Field Detection:
    entities:
      - binary_sensor.frontdoor_camera_field_detection
      - binary_sensor.driveway_camera_field_detection
      - binary_sensor.patio_camera_field_detection
      - binary_sensor.playarea_camera_field_detection

  Camera Line Crossing:
    entities:
      - binary_sensor.frontdoor_camera_line_crossing
      - binary_sensor.driveway_camera_line_crossing
      - binary_sensor.patio_camera_line_crossing
      - binary_sensor.playarea_camera_line_crossing

  Camera Tamper Detection:
    entities:
      - binary_sensor.frontdoor_camera_tamper_detection
      - binary_sensor.driveway_camera_tamper_detection
      - binary_sensor.patio_camera_tamper_detection
      - binary_sensor.playarea_camera_tamper_detection

camera:
  - platform: generic
    name: Driveway Camera
    still_image_url: !secret driveway_camera_url

switch:
  - platform: hikvisioncam
    name: Driveway Camera
    host: !secret driveway_camera_ip
    username: !secret hkcamera_username
    password: !secret hkcamera_password
#
# # ffmpeg:
# #   ffmpeg_bin: /usr/bin/ffmpeg
#
# # binary_sensor:
# #   - platform: ffmpeg_motion
# #     input: http://192.168.100.191:8080/video
binary_sensor:
  - platform: hikvision
    name: Driveway Camera
    host: !secret driveway_camera_ip
    username: !secret hkcamera_username
    password: !secret hkcamera_password
#
#
# android_ip_webcam:
#     host: 192.168.100.191
#     port: 8080
#     name: driveway
#     sensors:
#       # - audio_connections
#       - battery_level
#       - battery_temp
#       # - battery_voltage
#       # - light
#       # - motion
#       # - pressure

# camera:
#   - platform: mjpeg
#     name: Office camera
#     mjpeg_url: http://192.168.100.28:8100/Mjpeg/0?authToken=b799a8ea-cfa2-4098-9046-fbb55ac506f1

automation:
  - alias: Driveway camera
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.driveway_camera_line_crossing
          - binary_sensor.driveway_camera_field_detection
          - binary_sensor.skybell_front_door_motion
        from: 'off'
        to: 'on'
    # condition:
    #    - condition: state
    #      entity_id: device_tracker.brucesiphone2_ios
    #      state: 'not_home'
    action:
      - service: notify.slack__dev
        data_template:
           message: >
             {%- set responses = [
             'Motion detected near the driveway.',
             'Something or Someone is in the driveway',
             'I have notice activity in the driveway.'] -%}
             {{ responses | random }}
      - service: notify.ios_devices
        data_template:
          message: "Check {{ trigger.entity_id.split('.')[1].split('_')[0] | title }} camera."
          data:
            push:
              category: camera
            entity_id: "camera.{{ trigger.entity_id.split('.')[1].split('_')[0] ~ '' ~ '_camera' }}"
            attachment:
              url: "{{ states.camera[trigger.entity_id.split('.')[1].split('_')[0] ~ '' ~ '_camera'].attributes.entity_picture }}"
              content-type: jpg
