###################################
## [HikVision Cameras](http://amzn.to/2dcexIB)
###################################


homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'cameras'

      exposed: &exposed
        <<: *customize
        emulated_hue: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

# Driveway Camera
    binary_sensor.driveway_camera_motion:
      friendly_name: Driveway Camera Motion
    binary_sensor.driveway_camera_field_detection:
      friendly_name: Driveway Field Detection
    binary_sensor.driveway_camera_line_crossing:
      friendly_name: Driveway Line Crossing
    binary_sensor.driveway_camera_tamper_detection:
      friendly_name: Driveway Camera Tamper Detection

    group.camera_field_detection:
      <<: *hidden
    group.camera_line_crossing:
      <<: *hidden
    group.camera_tamper_detection:
      <<: *hidden

group:
  cameras:
    icon: mdi:video
    view: true
    entities:
    - camera.driveway_camera
    - group.skybell
    - group.camera_motion
    - group.camera_field_detection
    - group.camera_line_crossing
    - group.camera_tamper_detection



  Camera Motion:
    entities:
      - binary_sensor.frontdoor_camera_motion
      - binary_sensor.driveway_camera_motion
      - binary_sensor.patio_camera_motion
      - binary_sensor.playarea_camera_motion

  Camera Field Detection:
    entities:
      - binary_sensor.frontdoor_camera_field_detection
      - binary_sensor.driveway_camera_field_detection
      - binary_sensor.patio_camera_field_detection
      - binary_sensor.playarea_camera_field_detection

  Camera Line Crossing:
    entities:
      - binary_sensor.frontdoor_camera_line_crossing
      - binary_sensor.driveway_camera_line_crossing
      - binary_sensor.patio_camera_line_crossing
      - binary_sensor.playarea_camera_line_crossing

  Camera Tamper Detection:
    entities:
      - binary_sensor.frontdoor_camera_tamper_detection
      - binary_sensor.driveway_camera_tamper_detection
      - binary_sensor.patio_camera_tamper_detection
      - binary_sensor.playarea_camera_tamper_detection

camera:
  - platform: generic
    name: Driveway Camera
    still_image_url: !secret driveway_camera_url

switch:
  - platform: hikvisioncam
    name: Driveway Camera
    host: !secret driveway_camera_ip
    username: !secret hkcamera_username
    password: !secret hkcamera_password

binary_sensor:
  - platform: hikvision
    name: Driveway Camera
    host: !secret driveway_camera_ip
    username: !secret hkcamera_username
    password: !secret hkcamera_password

automation:
  - alias: Driveway camera motioneye
    trigger:
      - platform: webhook
        webhook_id: driveway_camera_motion
    # condition:
    #    - condition: state
    #      entity_id: device_tracker.brucesiphone2_ios
    #      state: 'not_home'
    action:
      # - service: notify.home
      #   data_template:
      #      message: >
      #        {%- set responses = [
      #        'Motion detected near the driveway.',
      #        'Something or Someone is in the driveway',
      #        'I have notice activity in the driveway.'] -%}
      #        {{ responses | random }}
      #     data:
      #       attachment:
      #         content-type: jpeg
      #       entity_id: camera.driveway_camera
      - service: notify.ios_devices
        data_template:
          message: >
            {%- set responses = [
            'Motion detected near the driveway.',
            'Something or Someone is in the driveway',
            'I have notice activity in the driveway.'] -%}
            {{ responses | random }}
          data:
            attachment:
              content-type: jpeg
            push:
              category: camera
            entity_id: camera.driveway_camera
