# android_ip_webcam:
#     host: 192.168.100.191
#     port: 8080
#     name: driveway
#     sensors:
#       # - audio_connections
#       - battery_level
#       - battery_temp
#       # - battery_voltage
#       # - light
#       # - motion
#       # - pressure

# camera:
#   - platform: mjpeg
#     name: Office camera
#     mjpeg_url: http://192.168.100.28:8100/Mjpeg/0?authToken=b799a8ea-cfa2-4098-9046-fbb55ac506f1

camera:
  - platform: generic
    name: Driveway Camera
    still_image_url: !secret driveway_camera_url

# ffmpeg:
#   ffmpeg_bin: /usr/bin/ffmpeg

# binary_sensor:
#   - platform: ffmpeg_motion
#     input: http://192.168.100.191:8080/video
binary_sensor:
  - platform: hikvision
    name: Driveway Camera
    host: !secret driveway_camera_ip
    username: !secret hkcamera_username
    password: !secret hkcamera_password


group:
  cameras:
    icon: mdi:video
    view: true
    entities:
    - camera.driveway_camera
    - group.skybell
    # - camera.office_camera
    # - binary_sensor.ffmpeg_motion
    # # - sensor.driveway_audio_connections
    # - sensor.driveway_battery_level
    # - sensor.driveway_battery_temp
    # - sensor.driveway_battery_voltage
    # - sensor.driveway_light
    # - sensor.driveway_motion
    # - sensor.driveway_pressure

# automation:
#   - alias: Driveway camera
#     trigger:
#       - platform: state
#         entity_id: binary_sensor.ffmpeg_motion
#         from: 'off'
#         to: 'on'
#     # condition:
#     #    - condition: state
#     #      entity_id: device_tracker.brucesiphone2_ios
#     #      state: 'not_home'
#     action:
#       - service: notify.slack__dev
#         data_template:
#            message: >
#              {%- set responses = [
#              'Motion detected near the driveway.',
#              'Something or Someone is in the driveway',
#              'I have notice activity in the driveway.'] -%}
#              {{ responses | random }}
#       - service: notify.ios_brucesiphone2_ios
#         data_template:
#            title: "Motion Detected"
#            message: >
#              {%- set responses = [
#              'Motion detected near the driveway.',
#              'Something or Someone is in the driveway',
#              'I have notice activity in the driveway.'] -%}
#              {{ responses | random }}
#            data:
#              push:
#                badge: 0
#                category: camera
#              entity_id: camera.driveway
#              attachment:
#                url: camera.driveway.attributes.entity_picture
#                content-type: jpg
