homeassistant:
  customize:
    device_tracker.bruce_iphone:
      icon: mdi:cellphone-iphone
      friendly_name: Bruce's Phone
    device_tracker.lene_iphone:
      icon: mdi:cellphone-iphone
      friendly_name: Lene's Phone
    device_tracker.kahlan_iphone:
      icon: mdi:cellphone-iphone
      friendly_name: Kahlan's phone
    device_tracker.breevsipad:
      icon: mdi:tablet-ipad
      friendly_name: Bruces's ipad
    person.bruce:
      entity_picture: /local/tw.png
    person.lene:
      entity_picture: /local/ml.png
    person.kahlan:
       entity_picture: /local/minion1.jpg

# input_boolean:
#   alert_delays:
#     initial: on

# group:
#   Transit:
#   - input_boolean.alert_delays
#   - sensor.Lene_to_home
#   - sensor.Bruce_to_home
#   - sensor.From_Home_to_Church
#   - sensor.to_CC
#   - proximity.lene_home
#   - proximity.bruce_home
#   - proximity.home
#   Maps:
#   - camera.bruce_map
#   - camera.lene_map

# camera:
#   - platform: generic
#     name: Bruce Map
#     still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.brucesiphone2_ios.attributes.latitude }},{{ states.device_tracker.brucesiphone2_ios.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:Bruce%7C{{ states.device_tracker.brucesiphone2_ios.attributes.latitude }},{{ states.device_tracker.brucesiphone2_ios.attributes.longitude }}
#     limit_refetch_to_url_change: true
#   - platform: generic
#     name: Lene Map
#     still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.leneiphone_ios.attributes.latitude }},{{ states.device_tracker.leneiphone_ios.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:Bruce%7C{{ states.device_tracker.leneiphone_ios.attributes.latitude }},{{ states.device_tracker.leneiphone_ios.attributes.longitude }}
#     limit_refetch_to_url_change: true


owntracks:
    max_gps_accuracy: 200


automation:
  - alias: Phone battery
    initial_state: True
    trigger:
      platform: numeric_state
      entity_id:
      - device_tracker.bruce_iphone
      - device_tracker.lene_iphone
      - device_tracker.kahlan_iphone
      - device_tracker.breevsipad
      value_template: '{{ state.attributes.battery }}'
      below: 30
    action:
      service: notify.dev
      data_template:
        message: >
          {{ trigger.to_state.attributes.friendly_name }}'s phone battery is low: {{ trigger.to_state.attributes.battery }}%

#################################################################
## Lights on 45 minutes before sunset
#################################################################

  - alias: 'Away lights On'
    initial_state: True
    condition:
      - condition: state
        entity_id: person.bruce
        state: 'not_home'
    trigger:
      - platform: sun
        event: sunset
        # offset: '-00:45:00'
    action:
      - service: homeassistant.turn_on
        entity_id: group.Bedroom_lamps
      # - service: logbook.log
      #   data_template:
      #     name: "Bedroom lamps On: "
      #      message: Turned lamps on via Automation
      - service: notify.dev
        data_template:
          message: >
            {%- set responses = [
            'It just tickles me pink to remind you that I turned the lights on for you.',
            'Got you covered, lamps are are on.'] -%}
            Bruce> {{ responses | random }}
