homeassistant:
  customize:
    binary_sensor.garage_door:
      friendly_name: Garage Door
    binary_sensor.laundry_room_door:
      friendly_name: Laundry Room Door
      device_class: opening

group:
  entry_points:
    name: Entry Points
    entities:
      - binary_sensor.laundry_room_door

  doors:
    name: Doors
    entities:
      - sensor.pantry_door
      - sensor.potter_closet
      - sensor.garage_door


sensor:
  - platform: template
    sensors:
      garage_door:
        friendly_name: 'Garage Door'
        value_template: "{{ 'Open' if is_state('binary_sensor.garage_door', 'on') else 'Closed' }}"
      laundry_door:
        friendly_name: 'Laundry Room Door'
        value_template: "{{ 'Open' if is_state('binary_sensor.laundry_room_door', 'on') else 'Closed' }}"
      pantry_door:
        friendly_name: 'Pantry Door'
        value_template: "{{ 'Open' if is_state('sensor.vision_zd2105us_5_recessed_door_window_sensor_alarm_level', '255') else 'Closed' }}"
      potter_closet:
        friendly_name: 'Potter Closet'
        value_template: "{{ 'Open' if is_state('sensor.vision_zd2105us_5_recessed_door_window_sensor_alarm_level_2', '255') else 'Closed' }}"


timer:
  laundry_door:
    duration: '00:00:30'
    # name: "Laundry Room"
  garage_door:
    duration: '00:00:30'

cover:
  - platform: template
    covers:
      garage_door:
        friendly_name: "Garage Door"
        value_template: "{{ 'Open' if is_state('binary_sensor.garage_door', 'on') else 'Closed' }}"
        open_cover:
          service: script.open_garage_door
        close_cover:
          service: script.close_garage_door
        stop_cover:
          service: script.stop_garage_door

automation:
  - alias: 'Turn on Driveway light Door open'
    initial_state: True
    condition:
      - condition: or  # 'when dark' condition: either after sunset or before sunrise
        conditions:
          - condition: sun
            after: sunset
            # offset: '-1:00:00'
          - condition: sun
            before: sunrise
      # - condition: template
      #   value_template: '{{ (as_timestamp(now()) - as_timestamp(states.input_boolean.gb_auto_off.last_changed)) > 180 }}'
      - condition: state
        entity_id: binary_sensor.garage_door
        state: 'on'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.sensor_2
          - binary_sensor.driveway_camera_line_crossing
          - binary_sensor.driveway_camera_field_detection
        to: 'on'
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.driveway_garage_light
      - service: notify.dev
        data_template:
          message: >
            Turning on the driveway light

  - alias: 'Turn off Driveway light Door Closed'
    initial_state: True
    condition:
      # - condition: or  # 'when dark' condition: either after sunset or before sunrise
      #   conditions:
      #     - condition: sun
      #       after: sunset
      #     - condition: sun
      #       before: sunrise
      - condition: template
        value_template: '{{ (as_timestamp(now()) - as_timestamp(states.switch.driveway_garage_light.last_changed)) > 300 }}'
      - condition: state
        entity_id: switch.driveway_garage_light
        state: 'on'
      - condition: state
        entity_id: binary_sensor.garage_door
        state: 'off'
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
    trigger:
      platform: time_pattern
      minutes: '/1'
      seconds: 00
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.driveway_garage_light
      - service: notify.dev
        data_template:
          message: >
            Turning off the driveway light

  # - alias: 'Garage Door open'
  #   initial_state: True
  #   trigger:
  #     - platform: state
  #       entity_id:
  #         - binary_sensor.garage_door
  #       to: 'on'
  #   action:
  #     - service: notify.ios_devices
  #       data:
  #         message: “Garage Door is open”
  #         data:
  #           push:
  #             # sound: "US-EN-Morgan-Freeman-Garage-Door-Opened.wav"
  #
  # - alias: 'Garage Door Closed'
  #   initial_state: True
  #   trigger:
  #     - platform: state
  #       entity_id:
  #         - binary_sensor.garage_door
  #       to: 'off'
  #   action:
  #     - service: notify.ios_devices
  #       data:
  #         message: “Garage Door is Closed”
  #         data:
  #           push:
  #             # sound: "US-EN-Morgan-Freeman-Garage-Door-Closed.wav"


  - alias: laundry_open
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.laundry_door
      from: 'Closed'
      to: 'Open'
    condition:
      condition: state
      entity_id: group.family
      state: 'home'
    action:
      - service: timer.start
        entity_id: timer.laundry_door

  - alias: Notify Door Open
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.laundry_door
    condition:
      condition: state
      entity_id: sensor.laundry_door
      state: 'Open'
    action:
      - service: script.speech_engine
        data_template:
          # DoorEvent: >
          #   {% set door = state_attr('sensor.laundry_door','friendly_name') %}
          #
          #   {%- macro door_sentence(door) -%}
          #   "The {{ door }}is open. Please close the door!"
          #
          #   {%- endmacro -%}
          #   ""{{door_sentence(door)}}"
          call_no_announcement: 1
          call_window_check: 1
      - service: timer.start
        entity_id: timer.laundry_door



# https://raw.githubusercontent.com/home-assistant/home-assistant-iOS/master/HomeAssistant/Sounds/MorganFreeman/US-EN-Morgan-Freeman-Garage-Door-Closed.wav
