homeassistant:
  customize:
    binary_sensor.garage_door:
      friendly_name: Garage Door
    binary_sensor.laundry_room_door:
      friendly_name: Laundry Room Door
      device_class: opening

group:
  entry_points:
    name: Entry Points
    entities:
      - binary_sensor.laundry_room_door

  doors:
    name: Doors
    entities:
      - sensor.pantry_door
      - sensor.potter_closet
      - sensor.garage_door


sensor:
  - platform: template
    sensors:
      garage_door:
        friendly_name: 'Garage Door'
        value_template: "{{ 'Open' if is_state('binary_sensor.garage_door', 'on') else 'Closed' }}"
      laundry_door:
        friendly_name: 'Laundry Room Door'
        value_template: "{{ 'Open' if is_state('binary_sensor.laundry_room_door', 'on') else 'Closed' }}"
      pantry_door:
        friendly_name: 'Pantry Door'
        value_template: "{{ 'Open' if is_state('sensor.vision_zd2105us_5_recessed_door_window_sensor_alarm_level', '255') else 'Closed' }}"
      potter_closet:
        friendly_name: 'Potter Closet'
        value_template: "{{ 'Open' if is_state('sensor.vision_zd2105us_5_recessed_door_window_sensor_alarm_level_2', '255') else 'Closed' }}"


timer:
  laundry_door:
    duration: '00:00:30'
    # name: "Laundry Room"
  garage_door:
    duration: '00:00:30'

cover:
  - platform: template
    covers:
      garage_door:
        friendly_name: "Garage Door"
        value_template: "{{ 'Open' if is_state('binary_sensor.garage_door', 'on') else 'Closed' }}"
        open_cover:
          service: script.open_garage_door
        close_cover:
          service: script.close_garage_door
        stop_cover:
          service: script.stop_garage_door

automation:
  - alias: laundry_open
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.laundry_door
      from: 'Closed'
      to: 'Open'
    condition:
      condition: state
      entity_id: group.family
      state: 'home'
    action:
      - service: timer.start
        entity_id: timer.laundry_door

  - alias: laundry_reset
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.laundry_door
      to: 'Closed'
      from: 'Open'
    condition:
      condition: state
      entity_id: group.family
      state: 'home'
    action:
      - service: timer.cancel
        entity_id: timer.laundry_door

  - alias: Notify Door Open
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.laundry_door
    condition:
      condition: state
      entity_id: sensor.laundry_door
      state: 'Open'
    action:
      - service: script.speech_engine
        data_template:
          call_no_announcement: 1
          doorevent: >
            {% set door = states.binary_sensor.laundry_room_door.attributes.friendly_name %}
            {%- macro doorevent(door) -%}
            {{ [
            "Hey you Guys!!! Some one left the " ~ door +" open.",
            "There is a draft of air coming in because the " ~ door +" is open",
            "The " ~ door +" needs to be closed.",
            "If only I could close the " ~ door +" for you guys, but alas I cannot. Please help me."
            ] | random }}
            {%- endmacro -%}
            "{{doorevent(door)}}"
      - service: timer.start
        entity_id: timer.laundry_door



# https://raw.githubusercontent.com/home-assistant/home-assistant-iOS/master/HomeAssistant/Sounds/MorganFreeman/US-EN-Morgan-Freeman-Garage-Door-Closed.wav
