##########  ############################################################
##  Morning wakeup for the kids
## 
##
##
######################################################################
homeassistant:
  customize:
    switch.kahlan_bed:
      icon: mdi:hotel 
      emulated_hue: true
      emulated_hue_name: "Kahlan Alarm"
      friendly_name: Kahlan Alarm

    switch.braelyn_bed:
      icon: mdi:hotel 
      emulated_hue: true
      emulated_hue_name: "Braelyn Alarm"
      friendly_name: Braelyn Alarm

    switch.kent_bed:
      icon: mdi:hotel 
      emulated_hue: true
      emulated_hue_name: "Kent Alarm"
      friendly_name: Kent Alarm
  
    switch.bennett_bed:
      icon: mdi:hotel 
      emulated_hue: true
      emulated_hue_name: "Bennett Alarm"
      friendly_name: Bennett Alarm      

    input_boolean.alarm_active:
      icon: mdi:clock 
      # emulated_hue: true
      # emulated_hue_name: "Bennett Alarm"
      friendly_name: Alarm Clock Activated  

    input_boolean.weekdays:
      icon: mdi:calendar 
      # emulated_hue: true
      # emulated_hue_name: "Bennett Alarm"
      friendly_name: Weekdays only  





group:
  Alarm Clock:
    name: Alarm Clock
    view: true
    icon: mdi:clock
    entities:
      - group.controls
      - group.kids
      - group.automations

  Controls:
    control: hidden
    entities:
      - input_slider.slider_hours
      - input_slider.slider_minutes
      # - input_select.alarm_tone
      - input_boolean.alarmweekday
      - input_boolean.alarm_active
  Kids:
    control: hidden
    entities:  
      - switch.kahlan_bed
      - switch.braelyn_bed
      - switch.kent_bed
      - switch.bennett_bed

  Automations:
    control: hidden
    entities:  
      - automation.kids_in_bed
      - automation.test_alarm_clock
      - automation.check_for_repeat
      - automation.reset_alarm
      - script.kids_tts_warn
      - script.kids_tts_wake


input_slider:
  slider_hours:
    name: Hours
    initial: 7
    min: 0
    max: 23
    step: 1

  slider_minutes:
    name: Minutes
    initial: 0
    min: 0
    max: 59
    step: 1

input_boolean:
  alarmweekday:
    name: Weekdays Only
    initial: off
    icon: mdi:alarm

  alarm_active:
    name: Alarm State
    initial: on
    icon: mdi:alarm

  alarm_has_gone_off:
    name: Alarm Has Gone off
    initial: off
    icon: mdi:alarm

# ###### SELECTORS
# input_select:
#   alarm_tone:
#     name: Alarm Tone
#     options:
#       - "-"
#       - Alarm 13sec
#       - Alarm Local
#       - Hit Remixes
#       - Play Radio
#       - 90s Hits
#     initial: Alarm 13sec
#     icon: mdi:radio


##################################
## MQTT Alarm States
##################################

switch:
  - platform: mqtt
    state_topic: "/home/inbed/kahlan"
    command_topic: "/home/inbed/kahlan"
    name: "kahlan_bed"
    retain: yes
    payload_on: "yes"
    payload_off: "no"
  - platform: mqtt
    state_topic: "/home/inbed/braelyn"
    command_topic: "/home/inbed/braelyn"
    name: "braelyn_bed"
    retain: yes
    payload_on: "yes"
    payload_off: "no"
  - platform: mqtt
    state_topic: "/home/inbed/kent"
    command_topic: "/home/inbed/kent"
    name: "kent_bed"
    retain: yes
    payload_on: "yes"
    payload_off: "no"
  - platform: mqtt
    state_topic: "/home/inbed/bennett"
    command_topic: "/home/inbed/bennett"
    name: "bennett_bed"
    retain: yes
    payload_on: "yes"
    payload_off: "no"

###############################################################################
#  Automation 
###############################################################################
automation:

## Set all the kids to in bed nightly 
  - alias: Kids in Bed
    trigger:
      - platform: time
        at: '20:46:00'
    # condition:
    #   - condition: state
    #     entity_id: group.kids
    #     state: 'no'
    action:
      service: switch.turn_on
      entity_id: 
        - switch.kahlan_bed
        - switch.braelyn_bed
        - switch.kent_bed
        - switch.bennett_bed

  - alias: 'Snooze'
    trigger:
      platform: time
      minutes: '/1'
      seconds: 00      
    condition:
      condition: and
      conditions:
        - condition: template ### Check if 9 minutes prior to the slider causes a negative. If so adjust the hour back one and use the formula to determine how many minutes back into the previous hour
          value_template: >
            {% if states.input_slider.slider_minutes.state |int -9 < 0 %}
              {% if as_timestamp(now())|timestamp_custom('%H', True) |int == states.input_slider.slider_hours.state |int - 1 |int %}
                true
              {% else %}
                false
              {% endif %}
            {% else %}
              {% if as_timestamp(now())|timestamp_custom('%H', True) |int == states.input_slider.slider_hours.state |int %}
                true
              {% else %}
                false
              {% endif %}
            {% endif %}    
        - condition: template 
          value_template: >
            {% if states.input_slider.slider_minutes.state |int -9 < 0 %}
              {% if as_timestamp(now())|timestamp_custom('%M', True) |int == states.input_slider.slider_minutes.state |int - 9 + 60 %}
                true
              {% else %}
                false
              {% endif %}
            {% else %}
              {% if as_timestamp(now())|timestamp_custom('%M', True) |int == states.input_slider.slider_minutes.state |int - 9 %}
                true
              {% else %}
                false
              {% endif %}
            {% endif %}    
        - condition: state
          entity_id: input_boolean.alarm_active
          state: 'on'
    action:
      - service: notify.slack__dev
        data_template:
          message: >
            Starting Snooze
      - service: script.kids_tts_warn

  - alias: 'Alarm Clock'
    trigger:
      platform: time
      minutes: '/1'
      seconds: 00      
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >
            {% if as_timestamp(now())|timestamp_custom('%H', True) |int == states.input_slider.slider_hours.state |int %}
              true
            {% else %}
              false
            {% endif %}
        - condition: template
          value_template: >
            {% if as_timestamp(now())|timestamp_custom('%M', True) |int == states.input_slider.slider_minutes.state |int %}
              true
            {% else %}
              false
            {% endif %}
        - condition: state
          entity_id: input_boolean.alarm_active
          state: 'on'
    action:
      - service: notify.slack__dev
        data_template:
          message: >
            Starting Alarm clock
      - service: script.kids_tts_wake

  - alias: 'Check for Repeat'
    trigger:
      platform: time
      minutes: '/1'
      seconds: 00
    condition: 
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_has_gone_off
          state: 'on'
        - condition: or
          conditions:
            - condition: state
              entity_id: switch.kahlan_bed
              state: 'on'
            - condition: state
              entity_id: switch.kent_bed
              state: 'on'
            - condition: state
              entity_id: switch.braelyn_bed
              state: 'on'
            - condition: state
              entity_id: switch.bennett_bed
              state: 'on'
    action:
      - service: script.kids_tts_wake_repeat

  - alias: 'Reset Alarm'
    trigger:
      platform: time
      minutes: '/1'
      seconds: '/30'
    condition: 
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_has_gone_off
          state: 'on'
        - condition: or
          conditions:
            - condition: state
              entity_id: switch.kahlan_bed
              state: 'off'
            - condition: state
              entity_id: switch.kent_bed
              state: 'off'
            - condition: state
              entity_id: switch.braelyn_bed
              state: 'off'
            - condition: state
              entity_id: switch.bennett_bed
              state: 'off'
    action:
        - service: homeassistant.turn_off
          entity_id: input_boolean.alarm_has_gone_off


## Test the alarm

  - alias: 'Test Alarm Clock'
    trigger:
      platform: state
      entity_id: input_boolean.alarmweekday
      from: 'off'
      to: 'on'    
    condition:
      condition: state
      entity_id: input_boolean.alarm_active
      state: 'on'
    action:
      - service: notify.slack__dev
        data_template:
          message: >
            Starting Alarm clock
      - service: script.kids_tts_wake

###########################################################
# Scripts
###########################################################

script:
    kids_tts_warn:
      sequence:
        - condition: state
          entity_id: input_boolean.alarm_active
          state: 'on'
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.volumio_tts
            volume_level: '0.7'      
        - service: tts.google_say
          data_template:
            entity_id: media_player.volumio_tts
            message: >
              It is about time to get up, you have 9 more minutes to sleep
        - service: notify.slack__dev
          data_template:
            message: >
              Kids Snooze Executed
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.volumio_tts
            volume_level: '0.4'
        - service: script.kids_tts_wake

    kids_tts_wake:
      sequence:
        - wait_template: >-
           {{ not is_state('media_player.volumio_tts', 'playing') }}
          timeout: 00:01:30
        - condition: template
          value_template: >
            {% if is_state('media_player.volumio_tts', 'playing') %}
            false
            {% else %}
            true
            {% endif %}
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.volumio_tts
            volume_level: '1'
        - service: media_player.play_media
          data_template:
            entity_id: 
              - media_player.volumio_tts
            media_content_id: "https://raw.githubusercontent.com/sixreeves/Home-AssistantConfig/master/sounds/Unusual-music-loop-120-bpm.mp3"
            media_content_type: audio/mp4
        - delay: '00:00:16'   
        - service: tts.google_say
          data_template:
            entity_id: media_player.volumio_tts
            message: >
              {% set time = 'Today is ' + states('sensor.date_weekday') + states('sensor.date_month') +  states('sensor.date_day') %}
              It is time to get up!! {{time}} It is time to get up
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.volumio_tts
            volume_level: '0.4'
        - service: notify.slack__dev
          data_template:
            message: >
              kids alarm started
        - service: homeassistant.turn_on
          entity_id: input_boolean.alarm_has_gone_off


    kids_tts_wake_repeat:
      sequence:
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.volumio_tts
            volume_level: '0.7'
        - service: media_player.play_media
          data_template:
            entity_id: 
              - media_player.volumio_tts
            media_content_id: "https://raw.githubusercontent.com/sixreeves/Home-AssistantConfig/master/sounds/Alarm-tone.mp3"
            media_content_type: audio/mp4
        - delay: '00:00:15'   
        - service: tts.google_say
          data_template:
            entity_id: media_player.volumio_tts
            message: >
              {% set time = 'Today is ' + states('sensor.date_weekday') + states('sensor.date_month') +  states('sensor.date_day') %}
              It is time to get up!! {{time}} It is time to get up
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.volumio_tts
            volume_level: '0.4'
        - service: notify.slack__dev
          data_template:
            message: >
              kids alarm repeated