##########  ############################################################
##  Morning wakeup for the kids
##
##
##
######################################################################
homeassistant:
  customize:
    switch.kahlan_bed:
      icon: mdi:hotel
      emulated_hue: true
      emulated_hue_name: "Kahlan Alarm"
      friendly_name: Kahlan Alarm

    switch.braelyn_bed:
      icon: mdi:hotel
      emulated_hue: true
      emulated_hue_name: "Braelyn Alarm"
      friendly_name: Braelyn Alarm

    switch.kent_bed:
      icon: mdi:hotel
      emulated_hue: true
      emulated_hue_name: "Kent Alarm"
      friendly_name: Kent Alarm

    switch.bennett_bed:
      icon: mdi:hotel
      emulated_hue: true
      emulated_hue_name: "Bennett Alarm"
      friendly_name: Bennett Alarm

    input_boolean.alarm_active:
      icon: mdi:clock
      # emulated_hue: true
      # emulated_hue_name: "Bennett Alarm"
      friendly_name: Alarm Clock Enabled

    input_boolean.alarm_weekday:
      icon: mdi:calendar
      # emulated_hue: true
      # emulated_hue_name: "Bennett Alarm"
      friendly_name: Weekdays only

    input_boolean.alarm_has_gone_off:
      icon: mdi:calendar
      friendly_name: Alarm is repeating




group:
  Controls:
    control: hidden
    entities:
      - input_slider.slider_hours
      - input_slider.slider_minutes
      # - input_select.alarm_tone
      - input_boolean.alarm_weekday
      - input_boolean.alarm_active
      - input_boolean.alarm_has_gone_off
  Kids:
    control: hidden
    entities:
      - sensor.alarm_status
      - switch.kahlan_bed
      - switch.braelyn_bed
      - switch.kent_bed
      - switch.bennett_bed

  Automations:
    control: hidden
    entities:
      - automation.kids_in_bed
      - automation.test_alarm_clock
      - automation.check_for_repeat
      - automation.reset_alarm
      - script.kids_tts_warn
      - script.kids_tts_wake


input_slider:
  slider_hours:
    name: Hours
    initial: 6
    min: 0
    max: 23
    step: 1

  slider_minutes:
    name: Minutes
    initial: 50
    min: 0
    max: 59
    step: 1

input_boolean:
  alarm_weekday:
    name: Weekdays Only
    initial: off
    icon: mdi:alarm

  alarm_active:
    name: Alarm State
    initial: on
    icon: mdi:alarm

  alarm_has_gone_off:
    name: Alarm Has Gone off
    initial: off
    icon: mdi:alarm

# ###### SELECTORS
# input_select:
#   alarm_tone:
#     name: Alarm Tone
#     options:
#       - "-"
#       - Alarm 13sec
#       - Alarm Local
#       - Hit Remixes
#       - Play Radio
#       - 90s Hits
#     initial: Alarm 13sec
#     icon: mdi:radio

sensor:
  - platform: template
    sensors:
      alarm_status:
        friendly_name: 'Alarm Status'
        value_template: >
          The Alarm is currently set to go off at {{ states("input_slider.slider_hours")|int }}:{{states("input_slider.slider_minutes")|int }}
          {% if states.input_slider.slider_minutes.state |int -9 < 0 %}
            so the snooze will start at {{ states("input_slider.slider_hours")|int - 1|int }}:{{states("input_slider.slider_minutes")|int - 9|int}}
          {% else %}
            so the snooze will start at {{ states("input_slider.slider_hours")|int }}:{{states("input_slider.slider_minutes")|int - 9|int}}
          {% endif %}
          Currently
          {% for state in states.switch -%}
            {%- if loop.first %}The {% elif loop.last %} and the {% else %}, the {% endif -%}
            {{ state.name }} is {{state.state}} {{- state.attributes.unit_of_measurement}}
          {%- endfor -%}.


##################################
## MQTT Alarm States
##################################

switch:
  - platform: mqtt
    state_topic: "/home/inbed/kahlan"
    command_topic: "/home/inbed/kahlan"
    name: "kahlan_bed"
    retain: yes
    payload_on: "yes"
    payload_off: "no"
  - platform: mqtt
    state_topic: "/home/inbed/braelyn"
    command_topic: "/home/inbed/braelyn"
    name: "braelyn_bed"
    retain: yes
    payload_on: "yes"
    payload_off: "no"
  - platform: mqtt
    state_topic: "/home/inbed/kent"
    command_topic: "/home/inbed/kent"
    name: "kent_bed"
    retain: yes
    payload_on: "yes"
    payload_off: "no"
  - platform: mqtt
    state_topic: "/home/inbed/bennett"
    command_topic: "/home/inbed/bennett"
    name: "bennett_bed"
    retain: yes
    payload_on: "yes"
    payload_off: "no"

###############################################################################
#  Automation
###############################################################################
automation:

## Set all the kids to in bed nightly
  - alias: Kids in Bed
    trigger:
      - platform: time
        at: '20:46:00'
    # condition:
    #   - condition: state
    #     entity_id: group.kids
    #     state: 'no'
    action:
      service: switch.turn_on
      entity_id:
        - switch.kahlan_bed
        - switch.braelyn_bed
        - switch.kent_bed
        - switch.bennett_bed

  - alias: 'Snooze'
    trigger:
      platform: time
      minutes: '/1'
      seconds: 00
    condition:
      condition: and
      conditions:
        - condition: template ### Check if 9 minutes prior to the slider causes a negative. If so adjust the hour back one and use the formula to determine how many minutes back into the previous hour
          value_template: >
            {% if states.input_slider.slider_minutes.state |int -9 < 0 %}
              {% if as_timestamp(now())|timestamp_custom('%H', True) |int == states.input_slider.slider_hours.state |int - 1 |int %}
                true
              {% else %}
                false
              {% endif %}
            {% else %}
              {% if as_timestamp(now())|timestamp_custom('%H', True) |int == states.input_slider.slider_hours.state |int %}
                true
              {% else %}
                false
              {% endif %}
            {% endif %}
        - condition: template
          value_template: >
            {% if states.input_slider.slider_minutes.state |int -9 < 0 %}
              {% if as_timestamp(now())|timestamp_custom('%M', True) |int == states.input_slider.slider_minutes.state |int - 9 + 60 %}
                true
              {% else %}
                false
              {% endif %}
            {% else %}
              {% if as_timestamp(now())|timestamp_custom('%M', True) |int == states.input_slider.slider_minutes.state |int - 9 %}
                true
              {% else %}
                false
              {% endif %}
            {% endif %}
        - condition: state
          entity_id: input_boolean.alarm_active
          state: 'on'
    action:
      # - service: logbook.log
      #   data_template:
      #     name: "Snooz Activated: "
      #     message: >-
      #       {{ state.sensor.alarm_status }}
      - service: notify.slack__dev
        data_template:
          message: Starting Snooze
      - service: script.kids_tts_warn

  - alias: 'Alarm Clock'
    trigger:
      platform: time
      minutes: '/1'
      seconds: 00
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >
            {% if as_timestamp(now())|timestamp_custom('%H', True) |int == states.input_slider.slider_hours.state |int %}
              true
            {% else %}
              false
            {% endif %}
        - condition: template
          value_template: >
            {% if as_timestamp(now())|timestamp_custom('%M', True) |int == states.input_slider.slider_minutes.state |int %}
              true
            {% else %}
              false
            {% endif %}
        - condition: state
          entity_id: input_boolean.alarm_active
          state: 'on'
    action:
      - service: notify.slack__dev
        data_template:
          message: Starting Alarm clock
      - service: script.kids_tts_wake

  - alias: 'Check for Repeat'
    trigger:
      platform: time
      minutes: '/1'
      seconds: 00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_has_gone_off
          state: 'on'
        - condition: state
          entity_id: group.kids
          state: 'on'
    action:
      - service: script.kids_tts_wake_repeat

  - alias: 'Reset Alarm'
    trigger:
      platform: time
      minutes: '/1'
      seconds: '/30'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_has_gone_off
          state: 'on'
        - condition: state
          entity_id: group.kids
          state: 'off'
    action:
        - service: homeassistant.turn_off
          entity_id: input_boolean.alarm_has_gone_off


## Test the alarm

  - alias: 'Test Alarm Clock'
    trigger:
      platform: state
      entity_id: input_boolean.alarm_weekday
      from: 'off'
      to: 'on'
    condition:
      condition: state
      entity_id: input_boolean.alarm_active
      state: 'on'
    action:
      - service: notify.slack__dev
        data_template:
          message: >
            Starting Alarm clock
      - service: script.kids_tts_wake

###########################################################
# Scripts
###########################################################

script:
    kids_tts_warn:
      sequence:
        # - condition: state
        #   entity_id: input_boolean.alarm_active
        #   state: 'on'
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.volumio_tts
            volume_level: '0.7'
        - service: tts.google_say
          data_template:
            entity_id: media_player.volumio_tts
            message: >
              It is about time to get up, you have 9 more minutes to sleep
        - service: notify.slack__dev
          data_template:
            message: Kids Snooze Executed
        # - service: logbook.log
        #   data_template:
        #     name: "Snooze Executed: "
        #     message: >-
        #       {{ state.sensor.alarm_status }}
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.volumio_tts
            volume_level: '1'


    kids_tts_wake:
      sequence:
        - wait_template: >-
           {{ not is_state('media_player.volumio_tts', 'playing') }}
          timeout: 00:01:30
        - condition: template
          value_template: >
            {% if is_state('media_player.volumio_tts', 'playing') %}
            false
            {% else %}
            true
            {% endif %}
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.volumio_tts
            volume_level: '1'
        - service: media_player.play_media
          data_template:
            entity_id:
              - media_player.volumio_tts
            media_content_id: "https://raw.githubusercontent.com/sixreeves/Home-AssistantConfig/master/sounds/Unusual-music-loop-120-bpm.mp3"
            media_content_type: audio/mp4
        - delay: '00:00:16'
        - service: tts.google_say
          data_template:
            entity_id: media_player.volumio_tts
            message: >
              {% set time = 'Today is ' + states('sensor.date_weekday') + states('sensor.date_month') +  states('sensor.date_day') %}
              It is time to get up!! {{time}} It is time to get up
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.volumio_tts
            volume_level: '1'
        # - service: logbook.log
        #   data_template:
        #     name: "Alarm Executed: "
        #     message: >-
        #       {{ state.sensor.alarm_status }}
        - service: homeassistant.turn_on
          entity_id: input_boolean.alarm_has_gone_off


    kids_tts_wake_repeat:
      sequence:
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.volumio_tts
            volume_level: '1'
        - service: media_player.play_media
          data_template:
            entity_id:
              - media_player.volumio_tts
            media_content_id: "https://raw.githubusercontent.com/sixreeves/Home-AssistantConfig/master/sounds/Alarm-tone.mp3"
            media_content_type: audio/mp4
        - delay: '00:00:15'
        - service: tts.google_say
          data_template:
            entity_id: media_player.volumio_tts
            message: >
              {% set time = 'Today is ' + states('sensor.date_weekday') + states('sensor.date_month') +  states('sensor.date_day') %}
              It is time to get up!! {{time}} It is time to get up
        # - service: media_player.volume_set
        #   data_template:
        #     entity_id: media_player.volumio_tts
        #     volume_level: '0.4'
        # - service: logbook.log
        #   data_template:
        #     name: "Alarm Executed: "
        #     message: >-
        #       {{ state.sensor.alarm_status }}
