##########  ############################################################
##  Morning wakeup for the kids
## 
##
##
######################################################################
homeassistant:
  customize:
    switch.kahlan_bed:
      icon: mdi:hotel 
      emulated_hue: true
      emulated_hue_name: "Kahlan Alarm"
      friendly_name: Kahlan Alarm

    switch.braelyn_bed:
      icon: mdi:hotel 
      emulated_hue: true
      emulated_hue_name: "Braelyn Alarm"
      friendly_name: Braelyn Alarm

    switch.kent_bed:
      icon: mdi:hotel 
      emulated_hue: true
      emulated_hue_name: "Kent Alarm"
      friendly_name: Kent Alarm
  
    switch.bennett_bed:
      icon: mdi:hotel 
      emulated_hue: true
      emulated_hue_name: "Bennett Alarm"
      friendly_name: Bennett Alarm      

group:
  Alarm Clock:
    name: Alarm Clock
    view: true
    icon: mdi:clock
    entities:
      - group.controls
      - group.kids

  Controls:
    control: hidden
    entities:
      - input_slider.slider_hours
      - input_slider.slider_minutes
      # - input_select.alarm_tone
      - input_boolean.alarmweekday
      - input_boolean.alarmstate
      - script.kids_tts_warn
      - script.kids_tts_wake

  kids:
    control: hidden
    entities:  
      - switch.kahlan_bed
      - switch.braelyn_bed
      - switch.kent_bed
      - switch.bennett_bed
      - automation.kids_in_bed

input_slider:
  slider_hours:
    name: Hours
    initial: 7
    min: 0
    max: 23
    step: 1

  slider_minutes:
    name: Minutes
    initial: 0
    min: 0
    max: 59
    step: 1

input_boolean:
  alarmweekday:
    name: Weekdays Only
    initial: off
    icon: mdi:alarm

  alarmstate:
    name: Alarm State
    initial: on
    icon: mdi:alarm

  alarm_has_gone_off:
    name: Alarm Has Gone off
    initial: off
    icon: mdi:alarm

# ###### SELECTORS
# input_select:
#   alarm_tone:
#     name: Alarm Tone
#     options:
#       - "-"
#       - Alarm 13sec
#       - Alarm Local
#       - Hit Remixes
#       - Play Radio
#       - 90s Hits
#     initial: Alarm 13sec
#     icon: mdi:radio


##################################
## MQTT Alarm States
##################################

switch:
  - platform: mqtt
    state_topic: "/home/inbed/kahlan"
    command_topic: "/home/inbed/kahlan"
    name: "kahlan_bed"
    retain: yes
    payload_on: "yes"
    payload_off: "no"
  - platform: mqtt
    state_topic: "/home/inbed/braelyn"
    command_topic: "/home/inbed/braelyn"
    name: "braelyn_bed"
    retain: yes
    payload_on: "yes"
    payload_off: "no"
  - platform: mqtt
    state_topic: "/home/inbed/kent"
    command_topic: "/home/inbed/kent"
    name: "kent_bed"
    retain: yes
    payload_on: "yes"
    payload_off: "no"
  - platform: mqtt
    state_topic: "/home/inbed/bennett"
    command_topic: "/home/inbed/bennett"
    name: "bennett_bed"
    retain: yes
    payload_on: "yes"
    payload_off: "no"

###############################################################################
#  Automation - Saves Switch State to MQTT
###############################################################################
automation:
  - alias: Kids in Bed
    trigger:
      - platform: time
        at: '20:46:00'
    # condition:
    #   - condition: state
    #     entity_id: group.kids
    #     state: 'no'
    action:
      service: switch.turn_on
      entity_id: 
        - switch.kahlan_bed
        - switch.braelyn_bed
        - switch.kent_bed
        - switch.bennett_bed

  - alias: 'Alarm Clock'
    trigger:
      platform: time
      # hours: '{% states.input_slider.slider_hours.state |int %}'
      # minutes: '{% states.input_slider.slider_minutes.state |int %}'
      # seconds: 00
      # platform: time
      at: '06:41:00'      
    condition:
      # - condition: template
      #   value_template: >
      #     {% if states.sensor.time.state.split(':')[0] |int == states.input_slider.slider_hours.state |int %}
      #       true
      #     {% else %}
      #       false
      #     {% endif %}
      # - condition: template
      #   value_template: >
      #     {% if states.sensor.time.state.split(':')[1]  |int == states.input_slider.slider_minutes.state |int %}
      #       true
      #     {% else %}
      #       false
      #     {% endif %}
      - condition: state
        entity_id: input_boolean.alarmstate
        state: 'on'
    action:
      - service: notify.slack__dev
        data_template:
          message: >
            Starting Alarm clock
      - service: script.kids_tts_warn

  - alias: 'Check for Repeat'
    trigger:
      platform: time
      minutes: '/1'
    condition: 
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_has_gone_off
          state: 'on'
        - condition: or
          conditions:
            - condition: state
              entity_id: switch.kahlan_bed
              state: 'on'
            - condition: state
              entity_id: switch.kent_bed
              state: 'on'
            - condition: state
              entity_id: switch.braelyn_bed
              state: 'on'
            - condition: state
              entity_id: switch.bennett_bed
              state: 'on'
    action:
      - service: script.kids_tts_wake_repeat

  - alias: 'Reset Alarm'
    trigger:
      platform: time
      minutes: '/1'
    condition: 
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_has_gone_off
          state: 'on'
        - condition: or
          conditions:
            - condition: state
              entity_id: switch.kahlan_bed
              state: 'off'
            - condition: state
              entity_id: switch.kent_bed
              state: 'off'
            - condition: state
              entity_id: switch.braelyn_bed
              state: 'off'
            - condition: state
              entity_id: switch.bennett_bed
              state: 'off'
    action:
        - service: homeassistant.turn_offn
          entity_id: input_boolean.alarm_has_gone_off

###########################################################
# Scripts
###########################################################

script:
    kids_tts_warn:
      sequence:
        - condition: state
          entity_id: input_boolean.alarmstate
          state: 'on'
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.volumio_tts
            volume_level: '0.7'      
        - service: tts.google_say
          data_template:
            entity_id: media_player.volumio_tts
            message: >
              It is about time to get up, you have 9 more minutes to sleep
        - service: notify.slack__dev
          data_template:
            message: >
              Kids Snooze Executed
        - delay: '00:9:00'
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.volumio_tts
            volume_level: '0.4'
        - service: script.kids_tts_wake

    kids_tts_wake:
      sequence:
        - wait_template: >-
           {{ not is_state('media_player.volumio_tts', 'playing') }}
          timeout: 00:01:30
        - condition: template
          value_template: >
            {% if is_state('media_player.volumio_tts', 'playing') %}
            false
            {% else %}
            true
            {% endif %}
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.volumio_tts
            volume_level: '0.7'
        - service: media_player.play_media
          data_template:
            entity_id: 
              - media_player.volumio_tts
            media_content_id: "https://raw.githubusercontent.com/sixreeves/Home-AssistantConfig/master/sounds/Unusual-music-loop-120-bpm.mp3"
            media_content_type: audio/mp4
        - delay: '00:00:16'   
        - service: tts.google_say
          data_template:
            entity_id: media_player.volumio_tts
            message: >
              {% set time = 'Today is ' + states('sensor.date_weekday') + states('sensor.date_month') +  states('sensor.date_day') %}
              It is time to get up!! {{time}} It is time to get up
        - delay: '00:00:10'
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.volumio_tts
            volume_level: '0.4'
        - service: notify.slack__dev
          data_template:
            message: >
              kids alarm is going off
        - service: homeassistant.turn_on
          entity_id: input_boolean.alarm_has_gone_off


    kids_tts_wake_repeat:
      sequence:
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.volumio_tts
            volume_level: '0.7'
        - service: media_player.play_media
          data_template:
            entity_id: 
              - media_player.volumio_tts
            media_content_id: "https://raw.githubusercontent.com/sixreeves/Home-AssistantConfig/master/sounds/Alarm-tone.mp3"
            media_content_type: audio/mp4
        - delay: '00:00:15'   
        - service: tts.google_say
          data_template:
            entity_id: media_player.volumio_tts
            message: >
              {% set time = 'Today is ' + states('sensor.date_weekday') + states('sensor.date_month') +  states('sensor.date_day') %}
              It is time to get up!! {{time}} It is time to get up
        - delay: '00:00:10'
        - service: media_player.volume_set
          data_template:
            entity_id: media_player.volumio_tts
            volume_level: '0.4'
        - service: notify.slack__dev
          data_template:
            message: >
              kids alarm is going off