##########  ############################################################
##  BRUH Multisensors nodes
##
##
##
######################################################################
# homeassistant:
#   customize:
    # switch.kahlan_bed:
    #   icon: mdi:hotel
    #   emulated_hue_hidden: true
    #   emulated_hue_name: "Kahlan Alarm"
    #   friendly_name: Kahlan Alarm
    #
    # input_boolean.alarm_active:
    #   icon: mdi:clock
    #   # emulated_hue_hidden: true
    #   # emulated_hue_name: "Bennett Alarm"
    #   friendly_name: Alarm Clock Enabled

group:
  sensor_node_1_card:
    name: Office Node
    icon: mdi:access-point
    entities:
      - sensor.office_temperature
      - sensor.office_humidity
      - sensor.office_ldr
      - sensor.office_pir
      # - light.office_led
  sensor_node_2_card:
    name: Living Room Node
    icon: mdi:access-point
    entities:
      - sensor.lv_temperature
      - sensor.lv_humidity
      - sensor.lv_ldr
      - sensor.lv_pir
      # - light.lv_led
  sensor_node_3_card:
    name: MB Room Node
    icon: mdi:access-point
    entities:
      # - sensor.lv_temperature
      # - sensor.lv_humidity
      # - sensor.lv_ldr
      - binary_sensor.mb_closet_pir
      # - light.lv_led
  sensor_node_4_card:
    name: Outside Sensors
    control: hidden
    entities:
      - binary_sensor.skybell_front_door_button
      - binary_sensor.skybell_front_door_motion
      - binary_sensor.driveway_camera_motion


# light:
#   - platform: mqtt_json
#     name: "Office LED"
#     state_topic: "bruh/sensornode1"
#     command_topic: "bruh/sensornode1/set"
#     brightness: true
#     flash: true
#     rgb: true
#     optimistic: false
#     qos: 0


sensor:
  - platform: mqtt
    state_topic: "bruh/sensornode1"
    name: "Office Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'

  - platform: mqtt
    state_topic: "bruh/sensornode1"
    name: "Office LDR"
    ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
    unit_of_measurement: "LUX"
    value_template: '{{ value_json.ldr }}'

  - platform: mqtt
    state_topic: "bruh/sensornode1"
    name: "Office PIR"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "bruh/sensornode1"
    name: "Office Temperature"
    unit_of_measurement: "째F"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "bruh/sensornode1"
    name: "Office Real Feel"
    unit_of_measurement: "째F"
    value_template: '{{ value_json.heatIndex | round(1) }}'

# Sensornode 2

  - platform: mqtt
    state_topic: "bruh/sensornode2"
    name: "LV Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'

  - platform: mqtt
    state_topic: "bruh/sensornode2"
    name: "LV LDR"
    ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
    unit_of_measurement: "LUX"
    value_template: '{{ value_json.ldr }}'

  - platform: mqtt
    state_topic: "bruh/sensornode2"
    name: "LV PIR"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "bruh/sensornode2"
    name: "LV Temperature"
    unit_of_measurement: "째F"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "bruh/sensornode2"
    name: "LV Real Feel"
    unit_of_measurement: "째F"
    value_template: '{{ value_json.heatIndex | round(1) }}'

# MB sensors
binary_sensor:
  - platform: mqtt
    state_topic: "homeassistant/binary_sensor/pir_mb_closet/state"
    name: "MB Closet PIR"
    device_class: motion
    payload_on: "on"
    payload_off: "off"
