################################################################
## Packages / Radio
################################################################
homeassistant:
  customize:
    script.radio:
      friendly_name: Start Radio
      icon: mdi:radio

###### STATE CARD
group:
  Radio:
    name: Radio
    entities:
      - input_select.radio_station_location
      - input_select.radio_station
      - input_slider.volume_radio
      - script.radio
      - script.stop

  players:
    name: media players
    entities:
      - media_player.volumio_tts
      - media_player.kodi_MB
      - media_player.kodi_LV


###### SELECT LOCATION AND STATION
script:
  radio:
    sequence:
      - service: media_player.play_media
        data_template:
          entity_id: >
            {% if is_state('input_select.radio_station_location', 'Kids') %} media_player.volumio_tts
            {% elif is_state('input_select.radio_station_location', 'Master bedroom') %} media_player.kodi_MB
            {% elif is_state('input_select.radio_station_location', 'All Zones') %} group.players
            {% endif %}
          media_content_id: >
            {% if is_state('input_select.radio_station', 'Jazz Groove') %} http://199.180.75.116:80/stream
            {% elif is_state('input_select.radio_station', 'Audiophile Jazz') %} http://174.127.85.10:8800
            {% elif is_state('input_select.radio_station', 'Classic Rock') %} http://198.27.70.26:10042/stream
            {% elif is_state('input_select.radio_station', 'Awesome 80s') %} http://104.200.142.184:80/1719_128
            {% elif is_state('input_select.radio_station', '90s Hits') %} http://rfcmedia.streamguys1.com/90hits.mp3
            {% endif %}
          media_content_type: 'audio/mp3'

  stop:
    sequence:
      - service: media_player.media_stop
        data_template:
          entity_id: >
            {% if is_state('input_select.radio_station_location', 'Kids') %} media_player.volumio_tts
            {% elif is_state('input_select.radio_station_location', 'Master bedroom') %} media_player.kodi_MB
            {% elif is_state('input_select.radio_station_location', 'All Zones') %} group.players
            {% endif %}

###### VOLUME SLIDER CONTROL (LOCATION BASED)
automation:
  - alias: 'Set Radio Volume'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_slider.volume_radio
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: >
            {% if is_state('input_select.radio_station_location', 'Kids') %} media_player.volumio_tts
            {% elif is_state('input_select.radio_station_location', 'Master bedroom') %} media_player.kodi_MB
            {% elif is_state('input_select.radio_station_location', 'All Zones') %} group.players
            {% endif %}
          volume_level: '{{  states.input_slider.volume_radio.state  }}'

input_slider:
  volume_radio:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05

###### SELECTORS
input_select:
  radio_station:
    name: Radio Station
    options:
      - "-"
      - Jazz Groove
      - Audiophile Jazz
      - Classic Rock
      - Awesome 80s
      - 90s Hits
    initial: "-"
    icon: mdi:radio
  radio_station_location:
    name: Radio Location
    options:
      - Kids
      - Master bedroom
      - All Zones
    initial: "All Zones"
    icon: mdi:radio

