homeassistant:
  customize:
    binary_sensor.tasmota_update_available:
      friendly_name: Update Available Tasmota
      device_class: problem

# Tasmota Firmware
# Getting Firmware from JSON for Tasmota
sensor:
  - platform: rest
    resource: https://api.github.com/repos/arendst/Sonoff-Tasmota/releases/latest
    name: Sonoff Firmware Version Available
    username: !secret githubuser
    password: !secret githubpass
    authentication: basic
    value_template: '{{ value_json.tag_name }}'
    headers:
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor
  - platform: mqtt
    name: "Sonoff Firmware"
    state_topic: "shellies/shellyswitch25-00C7AC/stat/STATUS2"
    value_template: 'v{{ value_json.StatusFWR.Version }}'
  - platform: mqtt
    name: "Switch Firmware"
    state_topic: "tele/smartplug1/stat/STATUS2"
    value_template: 'v{{ value_json.StatusFWR.Version }}'
binary_sensor:
  - platform: template
    sensors:
      tasmota_update_available:
        value_template: >-
          {{ (states.sensor.sonoff_firmware_version_available.state > states.sensor.sonoff_firmware.state) or (states.sensor.sonoff_firmware_version_available.state > states.sensor.switch_firmware.state)
              }}


automation:
  # - alias: "Power state on HA start-up"
  #   trigger:
  #     platform: homeassistant
  #     event: start
  #   action:
  #     - service: mqtt.publish
  #       data:
  #         topic: "cmnd/sonoffs/state"
  #         payload: ""

  - alias: MQTT Check on HA start-up
    trigger:
    - event: start
      platform: homeassistant
    action:
    - service: mqtt.publish
      data:
        payload: '2'
        topic: cmnd/sonoffs/status
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/state"
        payload: ""
    initial_state: 'true'
