################################################################
## Packages / live scenes
################################################################
homeassistant:
  customize:
    script.aquarium_scene:
      friendly_name: 'Aquarium'
      emulated_hue: true
      icon: mdi:fish
    script.sexy_time:
      friendly_name: 'Sexy Time'
      emulated_hue: true
      icon: mdi:heart
    script.river_scene:
      friendly_name: 'River'
      emulated_hue: true
      icon: mdi:hook
    script.beach_scene:
      friendly_name: 'Beach'
      emulated_hue: true
      icon: mdi:tower-beach
    script.jungle_scene:
      friendly_name: 'Jungle'
      emulated_hue: true
      icon: mdi:paw
    script.fireplace_scene:
      friendly_name: 'Fire Place'
      emulated_hue: true
      icon: mdi:fire
    script.space_scene:
      friendly_name: 'Space'
      emulated_hue: true
      icon: mdi:earth



script:
  space_scene:
    sequence:
      - service_template: >-
          script.kodi_play_file{{ '_bootup' if is_state('sensor.mb_mediacenter', 'Offline') }}
        data:
          file: "plugin://plugin.video.youtube/?action=play_video&videoid=NM2wtte1JRE"
      # - service: light.hue_activate_scene
      #   data:
      #     group_name: "Living Room"
      #     scene_name: "space"




sensor:
  - platform: example
  # - platform: miflora
  #   mac: 'xx:xx:xx:xx:xx:xx'
  #   name: Flower 1
  #   force_update: false
  #   median: 3
  #   monitored_conditions:
  #     - moisture
  #     - light
  #     - temperature
  #     - conductivity
  #     - battery


input_boolean:
  trash_test:  
    initial: off
#   weekly_trash_reminder:
#     initial: on
  test_tts:
    initial: off
  test_notify:  
    initial: off  
  test_hidegroup:  
    initial: off 

group:
  dev:
    icon: mdi:developer-board
    view: true
    entities:
    - sensor.example
    - input_boolean.trash_test
    - input_boolean.test_tts
    - input_boolean.switch_mode
    - input_boolean.test_hidegroup
    - group.live_scenes
    - sensor.date_weekday
    - sensor.date_month
    - sensor.date_day
 
  live_scenes:
    control: hidden
    name: Live Scenes
    entities:
      # - script.aquarium_scene
      # - script.river_scene
      # - script.beach_scene
      # - script.sexy_time
      # - script.jungle_scene
      - script.good_morning_tts
      - script.space_scene


automation:
   - alias: 'Test Weekly trash check'
     trigger:
       - platform: state
         entity_id: input_boolean.trash_test
         from: 'off'
         to: 'on'
     condition:
       # - condition: time
       #   weekday: 
       #     - sun
       - condition: state
         entity_id: input_boolean.weekly_trash_reminder
         state: 'on'
     action:
       # - service: notify.slack__dev
       #   data_template:
       #     message: >
       #       {%- set responses = [
       #       'Don\'t forget to set out the trash cans.',
       #       'Did you forget, the trash truck comes tomorrow?',
       #       'Got you covered, vacation lights are on'] -%}
       #       {{ responses | random }}
       - service: notify.ios_brucesiphone2_ios
         data_template:
           title: "Trash can reminder DEV"
           message: >
             {%- set responses = [
             'Don\'t forget to set out the trash cans.',
             'Did you forget, the trash truck comes tomorrow?',
             'Got you covered, vacation lights are on'] -%}
             {{ responses | random }}
           data:
             push:
               badge: 0
               category: "TRASH" 