################################################################
## Packages / live scenes
################################################################
homeassistant:
  customize:
    script.aquarium_scene:
      friendly_name: 'Aquarium'
      emulated_hue: true
      icon: mdi:fish
    script.sexy_time:
      friendly_name: 'Sexy Time'
      emulated_hue: true
      icon: mdi:heart
    script.river_scene:
      friendly_name: 'River'
      emulated_hue: true
      icon: mdi:hook
    script.beach_scene:
      friendly_name: 'Beach'
      emulated_hue: true
      icon: mdi:tower-beach
    script.jungle_scene:
      friendly_name: 'Jungle'
      emulated_hue: true
      icon: mdi:paw
    script.fireplace_scene:
      friendly_name: 'Fire Place'
      emulated_hue: true
      icon: mdi:fire
    script.space_scene:
      friendly_name: 'Space'
      emulated_hue: true
      icon: mdi:earth



script:
  space_scene:
    sequence:
      - service_template: >-
          script.kodi_play_file{{ '_bootup' if is_state('sensor.kodi_office', 'Offline') }}
        data:
          file: "plugin://plugin.video.youtube/?action=play_video&videoid=NM2wtte1JRE"
      # - service: light.hue_activate_scene
      #   data:
      #     group_name: "Living Room"
      #     scene_name: "space"
  test_speech_engine:
    sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.alert_mode

      - service: script.speech_engine
        data:
          call_no_announcement: 1
          call_dark_outside: 0
          call_inside_weather: 1
          call_responsibilities: 0
          call_outside_weather: 1
          call_garage_check: 1
          call_window_check: 0
          call_light_check: 1

  test_door_alert:
    sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.alert_mode

      - service: script.speech_engine
        data:
          call_no_announcement: 1
          # call_inside_weather: 1
          # call_responsibilities: 1
          # call_outside_weather: 1
          # call_garage_check: 1
          call_window_check: 1
          # call_light_check: 1

  tv_away:
    sequence:
      - service: media_extractor.play_media
        data_template:
          entity_id: media_player.living_room_cast
          media_content_id:  "https://www.youtube.com/watch?v=Pj0w0xo2ChY&list=PL71F771F239EF17F7"
          media_content_type: video/youtube

  tv_away_off:
    sequence:
      - service: media_player.media_stop
        data_template:
          entity_id: media_player.living_room_cast
      - service: media_player.turn_off
        data_template:
          entity_id: media_player.living_room_cast




sensor:
  - platform: template
    sensors:
      led_color:
        friendly_name: 'led_color'
        value_template: >
            {% if is_state('input_select.LED_Color', 'white') %} 0
            {% elif is_state('input_select.LED_Color', 'red') %} 1
            {% elif is_state('input_select.LED_Color', 'green') %} 2
            {% elif is_state('input_select.LED_Color', 'blue') %} 3
            {% elif is_state('input_select.LED_Color', 'magenta') %} 4
            {% elif is_state('input_select.LED_Color', 'yellow') %} 5
            {% elif is_state('input_select.LED_Color', 'cyan') %} 6
            {%- endif -%}




input_boolean:
  trash_test:
    initial: off
#   weekly_trash_reminder:
#     initial: on
  test_tts:
    initial: off
  test_notify:
    initial: off
  test_hidegroup:
    initial: off
  test_led_color:
    initial: off
  test_led_status:
    initial: off

input_select:
  led_color:
    name: LED Color Selector
    options:
      - white
      - red
      - green
      - blue
      - Magenta
      - Yellow
      - Cyan
    initial: white
    icon: mdi:light

group:
  dev:
    icon: mdi:developer-board
    view: true
    entities:
    - sensor.example
    - input_boolean.trash_test
    - group.family
    - switch.guest_mode
    - input_boolean.switch_mode
    - input_boolean.test_hidegroup
    - input_boolean.test_tts
    - input_select.led_color
    - group.live_scenes
    - sensor.date_weekday
    - sensor.date_month
    - sensor.date_day
    - script.test_speech_engine
    - script.test_door_alert
    - script.notify_office
    - sensor.last_message


  live_scenes:
    control: hidden
    name: Live Scenes
    entities:
      # - script.aquarium_scene
      # - script.river_scene
      # - script.beach_scene
      # - script.sexy_time
      # - script.jungle_scene
      - script.good_morning_tts
      - script.space_scene
      - script.tv_away
      - script.tv_away_off


automation:
   # - alias: 'Test Weekly trash check'
   #   initial_state: True
   #   trigger:
   #     - platform: state
   #       entity_id: input_boolean.trash_test
   #       from: 'off'
   #       to: 'on'
   #   condition:
   #     # - condition: time
   #     #   weekday:
   #     #     - sun
   #     - condition: state
   #       entity_id: input_boolean.weekly_trash_reminder
   #       state: 'on'
   #   action:
   #     # - service: notify.slack__dev
   #     #   data_template:
   #     #     message: >
   #     #       {%- set responses = [
   #     #       'Don\'t forget to set out the trash cans.',
   #     #       'Did you forget, the trash truck comes tomorrow?',
   #     #       'Got you covered, vacation lights are on'] -%}
   #     #       {{ responses | random }}
   #     - service: notify.ios_brucesiphone2_ios
   #       data_template:
   #         title: "Trash can reminder DEV"
   #         message: >
   #           {%- set responses = [
   #           'Don\'t forget to set out the trash cans.',
   #           'Did you forget, the trash truck comes tomorrow?',
   #           'Got you covered, vacation lights are on'] -%}
   #           {{ responses | random }}
   #         data:
   #           push:
   #             badge: 0
   #             category: "TRASH"

  - alias: Kitchen Dimmer - Test Blue
    trigger:
       - platform: state
         entity_id: input_boolean.trash_test
         from: 'off'
         to: 'on'
    action:
      - service: zwave.set_config_parameter
        data:
          node_id: 7
          parameter: 13
          value: 1
          size: 1
      - service: zwave.set_config_parameter
        data:
          node_id: 7
          parameter: 21
          value: 3


  - alias: Kitchen Dimmer - Test Off
    trigger:
       - platform: state
         entity_id: input_boolean.trash_test
         from: 'on'
         to: 'off'
    action:
      - service: zwave.set_config_parameter
        data:
          node_id: 7
          parameter: 13
          value: 0
          size: 1
      - service: zwave.set_config_parameter
        data:
          node_id: 7
          parameter: 21
          value: 0

  - alias: Kitchen Dimmer - LED Color
    trigger:
       - platform: state
         entity_id: input_select.led_color
    action:
      - service: zwave.set_config_parameter
        data:
          node_id: 7
          parameter: 14
          value: sensor.led_color
          size: 1
