homeassistant: 
  customize:
    input_boolean.trash:
      icon: mdi:delete-empty
    input_boolean.weekly_trash_reminder:
      icon: mdi:delete


input_boolean:
  trash:  
    initial: off
  weekly_trash_reminder:
    initial: on

automation:
   - alias: 'Trash needs to go out'
     trigger:
       - platform: state
         entity_id: input_boolean.trash
         from: 'off'
         to: 'on'
     action:
       - service: notify.slack__home
         data_template:
           message: >
             {%- set responses = [
             'Please check the trash soon.',
             'What, you can\'t smell this mess?',
             'YES SIR, prepare to launch trash can!!!'] -%}
             {{ responses | random }}

   - alias: 'Trash taken out'
     trigger:
       - platform: state
         entity_id: input_boolean.trash
         from: 'on'
         to: 'off'
     action:
       - service: notify.slack__home
         data_template:
           message: >
             {%- set responses = [
             'Trash emptied and bag replaced.',
             'Ahh, fresh air again, the trash is gone',
             'AFFIRMATIVE SIR, trash cans away!!!'] -%}
             {{ responses | random }}

   # - alias: 'Trash take out reminder'
   #   trigger:
   #     - platform: time
   #       minutes: '/5'
   #       seconds: 00
   #     - platform: state
   #       entity_id: input_boolean.trash
   #       state: 'on'
   #   action:
   #     - service: notify.slack__dev
   #       data_template:
   #         message: >
   #           {%- set responses = [
   #           'Trash reminder.',
   #           'Trash reminder.',
   #           'Trash reminder.'] -%}
   #           DEV> {{ responses | random }}

#################################################################
## Trash cans to curb reminder
#################################################################

   - alias: 'Weekly trash check'
     trigger:
       # - platform: sun
       #   event: sunset
       #   offset: '-00:45:00'
       - platform: time
         at: '16:00:00'
       - platform: time
         at: '17:00:00'
       - platform: time
         at: '18:00:00'
       - platform: time
         at: '19:00:00'
       - platform: time
         at: '20:00:00'
       - platform: time
         at: '21:00:00'
     condition:
       - condition: time
         weekday: 
           - sun
       - condition: state
         entity_id: input_boolean.weekly_trash_reminder
         state: 'on'
     action:
       - service: notify.slack__dev
         data_template:
           message: >
             {%- set responses = [
             'Don\'t forget to set out the trash cans.',
             'Did you forget, the trash truck comes tomorrow?',
             'Got you covered, vacation lights are on'] -%}
             {{ responses | random }}
       - service: notify.ios_brucesiphone2_ios
         data_template:
           title: "Trash can reminder"
           message: >
             {%- set responses = [
             'Don\'t forget to set out the trash cans.',
             'Did you forget, the trash truck comes tomorrow?',
             'Got you covered, vacation lights are on'] -%}
             {{ responses | random }}
           data:
             push:
               badge: 0
               category: "TRASH" 
   - alias: 'Trash cans set out'
     trigger:
       - platform: event
         event_type: ios.notification_action_fired
         event_data:
           actionName: Already_Done
     action:
       - service: homeassistant.turn_off
         entity_id: input_boolean.weekly_trash_reminder
       - service: notify.ios_brucesiphone2_ios
         data:
           message: "Great job!"
   - alias: Remind later
     initial_state: true
     hide_entity: true
     trigger:
       platform: event
       event_type: ios.notification_action_fired
       event_data:
         actionName: SILENCE_REMINDER
     action:
       - service: notify.ios_brucesiphone2_ios
         data:
           message: "Will remind you again in an hour!"
       - service: input_boolean.turn_on
         entity_id: input_boolean.weekly_trash_reminder


# #################################################################
# ## Morning check if not cleared
# #################################################################
   - alias: 'Reset Weekly check'
     condition:
       - condition: state
         entity_id: input_boolean.weekly_trash_reminder
         state: 'on'
       - condition: time
         weekday: 
           - mon     
     trigger:
       - platform: time
         at: '16:00:00'
     action:
       - service: notify.slack__dev
         data_template:
           message: >
             {%- set responses = [
             'Don\'t forget to setup the trash cans tonight.',
             'Trash day is tomorrow, don\'t forget.',
             'Did you set out the trash cans?'] -%}
             {{ responses | random }}