################################################################
## Packages / Utilities
################################################################
homeassistant:
  customize:
    script.backup_config:
      friendly_name: Backup Configuration
      icon: mdi:backup-restore
    script.update_ha:
      friendly_name: Update Home Assistant
      icon: mdi:package-variant
    script.restart_ha:
      friendly_name: Restart Home Assistant
      icon: mdi:restart
    script.restart_dasher:
      friendly_name: Restart Dasher
      icon: mdi:restart
    script.clear_log:
      friendly_name: 'Clear Log File'
      icon: mdi:eraser
    # script.refresh_devices:
    #   friendly_name: Refresh Devices
    #   icon: mdi:account-convert
    script.clear_tts_cache:
      friendly_name: Clear TTS cache
      icon: mdi:shredder
###### STATE CARD #######################################################
group:
  utilities:
    name: Utilities
    control: hidden
    entities:
      #- script.refresh_devices
      - script.restart_ha
      - script.update_ha
      - script.clear_log
      - script.clear_tts_cache
      - script.restart_dasher

  backup:
    name: Backup
    control: hidden
    entities:
      - automation.auto_backup
      - script.backup_config
      - sensor.last_commit
      - sensor.last_backup
#########################################################################
script:
  update_ha:
    sequence:
      - service: tts.clear_cache
      - service: shell_command.update_ha
  restart_ha:
    sequence:
      - service: homeassistant.turn_on
        entity_id: input_boolean.restarts
      - service: tts.clear_cache
      - service: shell_command.del_log
      - service: shell_command.restart_ha
  restart_dasher:
    sequence:
      - service: shell_command.restart_dasher
  clear_log:
     sequence:
       - service: shell_command.del_log
  backup_config:
     sequence:
       - service: tts.clear_cache
       - service: shell_command.backup_config
  # refresh_devices:
  #   sequence:
  #     - service: mqtt.publish
  #       data:
  #         topic: owntracks/bigdrakar/justin/cmd
  #         payload: '{"_type":"cmd","action":"reportLocation"}"'
  #     - service: mqtt.publish
  #       data:
  #         topic: owntracks/bigdrakar/nicole/cmd
  #         payload: '{"_type":"cmd","action":"reportLocation"}"'
  clear_tts_cache:
    sequence:
      - service: tts.clear_cache
#########################################################################
automation:
  # - alias: "Owntracks Refresh"
  #   initial_state: 'on'
  #   trigger:
  #     - platform: time
  #       minutes: '/5'
  #       seconds: 0
  #   action:
  #     - service: script.refresh_devices
  # - alias: "Dasher Rstart"
  #   initial_state: 'on'
  #   trigger:
  #     platform: state
  #     entity_id: sensor.process_dasher
  #     state: off
  #   action:
  #     - service: script.restart_dasher

  - alias: "Auto Backup"
    initial_state: 'on'
    trigger:
      platform: template
      value_template: "{{ states('sensor.last_commit') > states('sensor.last_backup') }}"
    action:
      - service: script.backup_config
#########################################################################
sensor:
###### Latest github Commit
  - platform: command_line
    command: "python /home/homeassistant/.homeassistant/shell/latest_commit.py"
    name: 'Last Commit'
    scan_interval: 60

###### Latest config backup
  - platform: command_line
    command: "python /home/homeassistant/.homeassistant/shell/latest_backup.py"
    name: 'Last Backup'
    scan_interval: 60

  - platform: sabnzbd
    host: !secret sabnzb_ip
    port: 8081
    api_key: !secret sabnzb_key
    monitored_variables:
      - 'current_status'
      - 'speed'
      - 'queue_size'
      - 'queue_remaining'
      - 'disk_size'
      - 'disk_free'

shell_command:
  backup_config: 'sudo bash /home/homeassistant/.homeassistant/shell/backup_config.sh'
  update_ha: 'sudo bash /home/homeassistant/.homeassistant/shell/update_ha.sh </dev/null >> /home/homeassistant/.homeassistant/shell/update_ha.log 2>&1 &'
  restart_ha: 'sudo hassctl restart'
  del_log: rm /home/homeassistant/.homeassistant/home-assistant.log && touch /home/homeassistant/.homeassistant/home-assistant.log && chown -R -v homeassistant:homeassistant /home/homeassistant/.homeassistant/home-assistant.log
  restart_dasher: 'sudo dasher restart'

# weblink:
#   entities:
#     - name: Router
#       url: http://192.168.1.1/
#     - name: Home Assistant
#       url: https://home-assistant.io
